### ISSUE TITLE
compaction changes the meaning of absolute IRIs in some cases

### ISSUE THREAD

**Issue by pchampin** [w3c/json-ld-api#104]
## The problem

Some absolute IRIs are undistinguishable from compact IRIs (e.g. `mailto:a@b.c` or `tag:champin.net,2019:xyz`). This is in fact the case for any IRI that has no double-slash after the first colon.

Now consider the following data (DATA1):
```json
{
  "tag:champin.net,2019:prop": "hello world"
}
```
Here, the property is interpreted (by expansion or RDF-serialization) as an absolute IRI, since there is no `tag` prefix to interpret it as a compact IRI.

Now consider the following context (CTX1):
```json
{"@context": {
    "tag": "http://example.org/ns/tag/"
}}
```

If we compact DATA1 with CTX1, we get DATA2:
```json
{
  "@context": {
    "tag": "http://example.org/ns/tag/"
  },
  "tag:champin.net,2019:prop": "hello world"
}
```
([try it in the playground](https://json-ld.org/playground/#startTab=tab-compacted&json-ld=%7B%22tag%3Achampin.net%2C2019%3Aprop%22%3A%22hello%20world%22%7D&context=%7B%22%40context%22%3A%7B%22tag%22%3A%22http%3A%2F%2Fexample.org%2Fns%2Ftag%2F%22%7D%7D)).

This is wrong because in DATA2, the property is now interpreted (by expansion or RDF-serialization) as `http://example.org/ns/tag/champin.net,2019:prop` as [shown in the playground](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%7B%22tag%22%3A%22http%3A%2F%2Fexample.org%2Fns%2Ftag%2F%22%7D%2C%22tag%3Achampin.net%2C2019%3Aprop%22%3A%22hello%20world%22%7D&context=%7B%22%40context%22%3A%7B%22tag%22%3A%22http%3A%2F%2Fexample.org%2Fns%2Ftag%2F%22%7D%7D).

The compaction algorithm should detect there will be a problem when 1) it would leave an absolute IRI unmodified AND 2) the active context contains a term definition matching that IRI's scheme – call this CONDITION1.

## Proposed solution 1

If CONDITION1 above is met, an error or a warning (although I would prefer an error) is raised. The rationale is that it is impossible to produce a JSON-LD document preserving this absolute IRI with the given context.

Probably this should only happen when the context has `"@version": 1.1` set, to not break backward compatibility -- even though this was a bug in JSON-LD 1.0 as well...

## Proposed solution 2

If CONDITION1 above is met, another context is included in the output data, which contains a fresh prefix resolving to the IRI's scheme. That fresh prefix is used to transform the absolute IRI:
```json
{
  "@context": [
    {
      "_abs_tag": "tag:"
    },
    {
      "tag": "http://example.org/ns/tag/"
    }
  ],
  "_abs_tag:champin.net,2019:prop": "hello world"
}
```
But is it acceptable for the compaction algorithm to output a different context than the one given as input? Also, it might be not trivial to coin a clash-less prefix.

## Proposed solution 3

Another option would be to have a microsyntax to force a string to be interpreted as an absolute IRI. This microsyntax would be used by the compaction algorithm whenever CONDITION1 above is detected. E.g.::
```json
{
  "@context": {
    "tag": "http://example.org/ns/tag/"
  },
  "<tag:champin.net,2019:prop>": "hello world"
}
```

It could also be used by data authors to address the issue raised by w3c/json-ld-syntax/issues/177.

Proposed microsyntaxes:

* put the IRI between pointy brackets, as is done in Turtle: `"<tag:champin.net,2019:prop>"`
* prefix the IRI with a new "keyword-like" prefix: `"@abs:tag:champin.net,2019:prop"`

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-06-14-json-ld#section3-2).

- `ACTION:  write another proposed solution to #104 (which may also solve for #87 or perhaps #76) (Gregg Kellogg)`
<details><summary><i class="differentiate">View the transcript</i></summary>
ompaction changes the meaning of absolute IRIs in some cases #104<br/>
Gregg Kellogg: <a href="https://github.com/w3c/json-ld-api/issues/104">https://github.com/w3c/json-ld-api/issues/104</a><br/>
Pierre-Antoine Champin: the problem: through compaction, I can end up with a different graph than I started with<br/>
… i thin this is a 1.0 problem as well<br/>
Adam Soroka: .. there are examples in the issue that display the problem<br/>
Pierre-Antoine Champin: there is shown an IRI that is indistinguishable from an IRI.<br/>
… you can tell which it is only from context<br/>
Gregg Kellogg: there are other things that you can add to a context that would change the interpretation of things<br/>
… [gives example of similar phenomenon using lang tags]<br/>
… this goes right back the previous discussion<br/>
… you might want to say here that <code>@prefix=false</code><br/>
Dave Longley: +1 to <code>@prefix:</code> false to solve this<br/>
Gregg Kellogg: which could impact the expansion algo to not use it in this case<br/>
… but that could still be surprising<br/>
Pierre-Antoine Champin: { "<a href="http://ex.co/prop":">http://ex.co/prop":</a> "foo" }<br/>
Pierre-Antoine Champin: consider my example above<br/>
… and compact it with a context that I just recited out loud<br/>
Gregg Kellogg: there is no compaction w/o expansion<br/>
… but what is the context used for expansion?<br/>
Pierre-Antoine Champin: okay, yeah. I didn’t want to show expansion for brevity<br/>
… i can get this phenomenon using the same context for compaction and expansion<br/>
Dave Longley: adding the context he verbalized, you can no longer distinguish between the two uses of the term<br/>
Gregg Kellogg: even with a mechanism to prevent that, mistakes will appear<br/>
… if this was one line in 10,000 triples<br/>
… it might get missed<br/>
Pierre-Antoine Champin: if I expand and compact with the same context, it should round-trip, right?<br/>
Gregg Kellogg: yes<br/>
… but the semantics would change<br/>
Pierre-Antoine Champin: if we had a way to say that something isn’t a CURIE<br/>
… that would solve it<br/>
Adam Soroka: .. compaction should protect certain IRIS<br/>
Pierre-Antoine Champin: when compaction sees a term matching an IRI scheme, the problem can arise<br/>
… I made three proposals, bt I prefer the third<br/>
… i don’t like µsyntax, but…<br/>
Gregg Kellogg: a 4th proposal is to use <code>@prefix=false</code> during expansion<br/>
Pierre-Antoine Champin: I can’t always move my data out of th way of this<br/>
… . my contexts may be coming from someone else<br/>
Gregg Kellogg: <code>@prefix=false</code> can prevent this problem. maybe not perfectly<br/>
… going back to the dawn of time, we had to make some choice because of JSON<br/>
… this may be a bubble we are pushing around,<br/>
Dave Longley: I would formally object to proposal 3; I hate µsyntaxes<br/>
… this might be a corner case we can’t solve because of previous decisions, in the sense that<br/>
… there may be contexts you just can’t use with your data<br/>
… I wish we had not done CURIEs at all<br/>
… it was probably a mistake<br/>
… they introduce surprise<br/>
… we may have to accept certain corner cases<br/>
… it might require some kind of processing mode change, it might be a 2.0 issue<br/>
Gregg Kellogg: +1 to dlongley<br/>
Benjamin Young: we are wrangling a pass the of issues<br/>
… gkellogg: do you still think we could make <code>@prefix</code> clearer?<br/>
Dave Longley: <code>@prefix:</code> false would solve this in some cases<br/>
Gregg Kellogg: we already detect whether a term could be used as a prefix<br/>
… it’s an addition of ½ a line<br/>
… it’s a simple change<br/>
… it’s gets more complicated when we bring in different modes<br/>
… but the easy play is to make it symmetrical from compaction to expansion<br/>
… which would solve #104<br/>
… by offering a context author a way to avoid that problem<br/>
… it might solve #87 or #76<br/>
Benjamin Young: this merits an action at this point, not resolution<br/>
Action #1: write another proposed solution to #104 (which may also solve for #87 or perhaps #76) (Gregg Kellogg)<br/>
Pierre-Antoine Champin: i agree with this action, but I don’t think it will solve #104<br/>
… where dlongely’s position is my solution 1<br/>
… some contexts simply cannot work with some data<br/>
… if we cannot provide a solution, we should at least have an answer ready<br/>
Gregg Kellogg: if you create the opportunity for this collision, we should raise a warning<br/>
Dave Longley: it’s an error<br/>
Dave Longley: in my view<br/>
Pierre-Antoine Champin: one could bring in a local context<br/>
<b>gkelllogg:</b> bleh<br/>
</details>
