### ISSUE TITLE
Should rel="alternate" keep the base IRI of the original document?

### ISSUE THREAD

**Issue by pchampin** [w3c/json-ld-api#139]
This issue was first raised in [a comment to #133](https://github.com/w3c/json-ld-api/pull/133#discussion_r313726695), which was unfortunately not located on the right lines of the patch. It should have been about [line 5833](https://github.com/w3c/json-ld-api/pull/133/files/af1c48d30437c5b15e6faf62244b2f29ccdc6ddc#diff-eacf331f0ffc35d4b482f1d15a887d3bR5833).

To summarize, PR #133 states that, when dereferencing a URL to a non JSON-LD content, a JSON-LD must follow a Link HTTP header with rel="alternate" and type="application/ld+json", if available. This is perceived as some kind of "client-side content management", and I am very happy with it.

My concern is about [line 5833](https://github.com/w3c/json-ld-api/pull/133/files/af1c48d30437c5b15e6faf62244b2f29ccdc6ddc#diff-eacf331f0ffc35d4b482f1d15a887d3bR5833), which states that the processor must then behave as if the target of the Link had been directly retrieved from the original URL (i.e. the source of the Link).

So if I get text/html from `http://example.org/`, with a Link to `https://example.org/data/context.jsonld`, and the latter contains `"@id": "#foo"`, this should be interpreter as `http://example.org/#foo`, **rather than** `https://example.org/data/context.jsonld#foo`.

If that was transparent content-negogication (i.e. the client never explicitly fetches the second URL), then that would be ok. But as there is an explicit fetch of the second URL, this is more akin to 303 redirect, or more precisely, to content-negociation + 303 redirect as used by many RDF sources (such as DBPedia) and described by [Jeni Tennison](http://www.jenitennison.com/2012/05/11/using-punning-to-answer-httprange-14.html). 

And as far as I can tell, there is no precedent where relative IRIs after a redirect are interpreted with the base of the source (i.e. as if the redirect had not happened). While I see how it makes sense from the point of view of semantics, I'm concerned that this would make JSON-LD processors behave differently from other HTTP clients.

**Comment by BigBlueHat** [comment]
Good thoughts, @pchampin. There's also a potential confusion around multiple initial URLs using this `rel="alternate"` approach to result in the same context document.

If we keep the original request URL as the (initial) base value, then one might end up with one context document (processed from different originating URLs) outputting very different IRIs for its terms.

Think `http://example.com/schema/` vs. `http://example.com/schema/v2/` both of which might use a `rel="alternate"` pointed at `http://example.com/schema/context.jsonld`. Without that document using `@base` or absolute IRIs, the output IRIs would be prefixed with either of those URLs...and never the context document.

So...leaving the Request-URI the same after the `rel="alternate"` is handled does indeed have risk and confusion potential...

In the end, I think we're running up against something similar to "being vague (or conditional) about base is bad." 😃

**Comment by rubensworks** [comment]
I share this concern. My gut feeling also says that it makes more sense to have the base set to the linked URL.

As this is is really about the _client_ following links, the client should IMO not be expected to remember the state of the previous request to determine the base of the next request. As far as I know, there are no cases where documents should be handled differently based on what links were followed to reach it (please tell me if those _do_ exist). This feels very non-RESTful to me.

Building upon @pchampin's example from above,
this would mean that the content of `https://example.org/data/context.jsonld` would mean something different if it was loaded via `https://example.org/data/context.jsonld` directly, versus when it was loaded via `https://example.org/`.

**Comment by BigBlueHat** [comment]
> As far as I know, there are no cases where documents should be handled differently based on what links were followed to reach it (please tell me if those _do_ exist). This feels very non-RESTful to me.

Content Negotiation. But that is explicitly serving multiple "equivalent" resource representations, so they should all share the same link semantics, and if they don't, the error is the authors...not the HTTP clients.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-08-23-json-ld#section4-2).

- `RESOLVED:  Agree with the issue and by default associate base with the redirected URL not the original`
- `ACTION:  add use absolute URIs to BPs (Benjamin Young)`
- `ACTION:  add use absolute URIs to BPs (Adam Soroka)`
<details><summary><i class="differentiate">View the transcript</i></summary>
Rob Sanderson: API issue #139<br/>
Pierre-Antoine Champin: In the current API spec, it says whenever a rel="alternate" link is followed the base URL is set to the original URL. Meaning that relative URLs in a context document should be resolved as if found in the HTML document that is the source of the link.<br/>
… I see this partly as content negotiation which would advocate for this but also as a redirection because the client has to explicitly follow a link. I don’t know of such a situation that causes this to happen. I understand the rationale but it has no precedent.<br/>
… And it creates a strange exception and that’s my concern.<br/>
Pierre-Antoine Champin: dlongley: as I understand, Gregg thought that was consistent with how things work elsewhere.<br/>
Pierre-Antoine Champin: … And what we are already doing.<br/>
Pierre-Antoine Champin: … My position would be: let’s not do something that is exceptional.<br/>
Pierre-Antoine Champin: … But let’s not break what we are doing now either.<br/>
Rob Sanderson: also +1 to dlongley<br/>
Rob Sanderson: and to pchampin / bigbluehat about setting default <code>@base</code><br/>
Benjamin Young: +1 to what Dave just said but it’s also about setting the default base. Maybe we can follow this up with a note around it. Context authors should be explicit about setting their own base or using URLs for their contexts because there are a host of situations where base is flaky.<br/>
… Publishing a context where you’re not being explicit is dangerous anyway already – and these things, certainly both of them combined, make it much less dependable. It could come with a declaration that context authors need to be explicit about their base or use full URLs.<br/>
Adam Soroka: +1 to what Dave and Ben said. If I understand correctly we’re talking about a link between two resources, such that you traverse that link you’re going to interpret base with the original document. You could in theory interpret with a different base – that’s not some kind of world is going to fall, but it opens the door to a lot of potential confusion. Especially in complex systems where you get a lot of reuse.<br/>
Ivan Herman: I come back to what Benjamin said – if there is an <code>@base</code> in the <code>@context</code> document doesn’t that set the base that refers to the document.<br/>
… If it does, then we shouldn’t do that.<br/>
Benjamin Young: The <code>@base</code> only works for the document it’s in, not in the <code>@context,</code> only works in an inline context, not for a remote context.<br/>
Ivan Herman: Ok.<br/>
Benjamin Young: It’s not about removing rel="alternate" it’s about not setting base to the original request URI but setting it to the redirect meaning rather than the original one.<br/>
Pierre-Antoine Champin: dlongley: in schema.org, I think that all the URLs are explicit. I’m pretty sure they would want their base URL be <a href="http://schema.org,">http://schema.org,</a> not any URL they redirect to.<br/>
Pierre-Antoine Champin: … Let’s make sure we are not shooting ourselves in the foot.<br/>
Ivan Herman: schema.org uses only absolute URLs.<br/>
Benjamin Young: Part of this closing proposal – should we add something in the NOTE or something … that context authors should always be explicit with their URLs because it’s risky at best.<br/>
Ivan Herman: Whomever is the editor of the best practices document should make a note.<br/>
Action #4: add use absolute URIs to BPs (Benjamin Young)<br/>
Action #5: add use absolute URIs to BPs (Adam Soroka)<br/>
Proposed resolution: Agree with the issue and by default associate base with the redirected URL not the original (Rob Sanderson)<br/>
Rob Sanderson: +1<br/>
Ivan Herman: +1<br/>
Ruben Taelman: +1<br/>
Dave Longley: +1 (hopes this is the right decision)<br/>
Pierre-Antoine Champin: +1<br/>
Benjamin Young: +1<br/>
Resolution #3: Agree with the issue and by default associate base with the redirected URL not the original<br/>
Adam Soroka: +1<br/>
</details>
