### ISSUE TITLE
keyword alias with `"@prefix"=true` ?

### ISSUE THREAD

**Issue by pchampin** [w3c/json-ld-api#153]
The following is quite ugly, and in my opinion it should break.
```
{
  "@context": {
    "@version": 1.1,
    "id": {
        "@id": "@id",
        "@prefix": true
     }
  },
  "id:foo": "#x"
}
```
The thing is: nothing in the spec explicitly prevents it:
* Step 25 of [Create Term Definition](https://w3c.github.io/json-ld-api/#algorithm-0) does not check that `iri mapping` is not a keyword.
* Step 5.4 of [IRI Expansion](https://w3c.github.io/json-ld-api/#algorithm-1) does not either, so should happily use the keyword as a prefix.

This is what the Ruby distiller is doing: the JSON-LD above generates a "@idfoo" property... The playground ignores it silently, which in my view is not complying with the spec. But that's not the point. I think the spec should reject the use of keyword aliases as prefix, by updating either of the steps above.

I can provide the PR, if we agree that it's a bug and not a feature.

**Comment by azaroth42** [comment]
Related to https://github.com/w3c/json-ld-syntax/issues/246

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-09-20-json-ld#section5-1).

- `RESOLVED:  When encountering a term in the form of a compact IRI for which the prefix would expand to a keyword, do not expand the term`
- `ACTION:  determine if <code>@prefix:</code> false will prevent the term from being used in expanding IRIs, and file an issue if it does (Gregg Kellogg)`
<details><summary><i class="differentiate">View the transcript</i></summary>
Rob Sanderson: time to summarize for the minutes<br/>
… we accept that issue 153 is an issue<br/>
Gregg Kellogg: a bug<br/>
Rob Sanderson: true. a bug<br/>
… it should not in fact generate <code>@idfoo</code><br/>
Gregg Kellogg: it should treat id:foo as an IRI<br/>
… so the result of expanding should be id:foo<br/>
Proposed resolution: When encountering a term in the form of a compact IRI for which the prefix would expand to a keyword, do not expand the term (Rob Sanderson)<br/>
Rob Sanderson: so if there was an <code>@vocab</code> it would expand to that value + id:foo?<br/>
Rob Sanderson: +1<br/>
Pierre-Antoine Champin: +1<br/>
Gregg Kellogg: it won’t be expanded as a relative URI because of the colon<br/>
Gregg Kellogg: +1<br/>
Benjamin Young: +1<br/>
Simon Steyskal: +1<br/>
Resolution #4: When encountering a term in the form of a compact IRI for which the prefix would expand to a keyword, do not expand the term<br/>
Gregg Kellogg: if there is an id term that’s legit, and I see <code>@prefix:</code> false<br/>
… it won’t expand that because prefix is false<br/>
Action #1: determine if <code>@prefix:</code> false will prevent the term from being used in expanding IRIs, and file an issue if it does (Gregg Kellogg)<br/>
</details>

**Comment by pchampin** [comment]
(duplicating my comment on c482f45, to make the discussion easier to follow:

> It seems to me that this change was meant precisely to prevent a term from being used in expanding IRIs when @prefix is false...

From what I see, the `Expand IRI` algorithm in the Ruby distiller does honnor `@prefix`, conforming to the letter of the spec since c482f45 (but possibly not conforming to its spirit). The Playground does *not* honnor `@prefix` during expansion.

My PR above is based on the current version of `Expand IRI`. If we were to revert it to *not* honnor `@prefix`, it would be moot.

**Comment by gkellogg** [comment]
WG [resolved to close the issue as complete](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-10-18-json-ld#resolution2).
