### ISSUE TITLE
lazy-evaluation of 1.1 mode

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-api#161]
As discussed at the F2F, we will consider making version announcement a suggestion, rather than a requirement, particularly where the feature would either be ignored or flagged by an existing 1.0 processor. We will evaluate the issues for 1.0 processors encountering 1.1 features without version announcement on a case-by-case basis. Version announcement remains a best-practice.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-10-18-json-ld#section2-2).

- `RESOLVED:  Accept changes after changing clause for explicit 1.1 for API #161, lazy evaluation of processing mode`
<details><summary><i class="differentiate">View the transcript</i></summary>
Lazy evaluation of 1.1 processing mode<br/>
Rob Sanderson: <a href="https://github.com/w3c/json-ld-api/issues/161">https://github.com/w3c/json-ld-api/issues/161</a><br/>
Gregg Kellogg: Also <a href="https://github.com/w3c/json-ld-syntax/pull/284">https://github.com/w3c/json-ld-syntax/pull/284</a><br/>
Gregg Kellogg: <a href="https://github.com/w3c/json-ld-framing/pull/76">https://github.com/w3c/json-ld-framing/pull/76</a><br/>
Gregg Kellogg: <a href="https://github.com/w3c/json-ld-api/pull/170">https://github.com/w3c/json-ld-api/pull/170</a><br/>
Rob Sanderson: It would be easier for version migration compliance to handle <code>@version</code> keyword lazily, and let processors detect them based on the features that are being used.<br/>
Gregg Kellogg: When we discussed it, the idea was that we would do feature detection, and move up to 1.1 when we saw that.<br/>
… If you are explicitly in 1.0 mode, then you don’t run any 1.1 features. If one such feature would be 1.1, then a 1.0 processor would terminate.<br/>
… This would happen in any case on old processors if they see unknown (new) features.<br/>
… The PRs describe this slight change and the necessary steps.<br/>
Dave Longley: +1 to gregg’s description of how lazy eval works<br/>
Rob Sanderson: There was a question about the tests to see if there were any issues.<br/>
Gregg Kellogg: There weren’t any exceptions. I just added a couple of tests.<br/>
… I’ve updated many tests that used to the processing mode explicitly, and things seem to work correctly.<br/>
Dave Longley: As we will probably will have a JSON-LD 1.2 at some point, we don’t want to lock down the version in the algorithm.<br/>
Ivan Herman: +1 dlongley<br/>
Gregg Kellogg: I agree.<br/>
Rob Sanderson: +1 as well<br/>
Rob Sanderson: Is this written like that in the PRs?<br/>
Dave Longley: +1 to remove those clauses<br/>
Gregg Kellogg: Yes, the PRs make it so that processing mode can be “unset”, which allows the silent upgrade.<br/>
Dave Longley: +1 to merge the PRs with the above changes<br/>
Ivan Herman: +1 for me, too<br/>
Gregg Kellogg: The conformance section describes changes to proc mode as well, besides the algorithmic changes.<br/>
Proposed resolution: Accept changes after changing clause for explicit 1.1 for API #161, lazy evaluation of processing mode (Rob Sanderson)<br/>
Rob Sanderson: +1<br/>
Gregg Kellogg: +1<br/>
Ruben Taelman: +1<br/>
Dave Longley: +1<br/>
David I. Lehn: +1<br/>
Pierre-Antoine Champin: +1<br/>
Resolution #3: Accept changes after changing clause for explicit 1.1 for API #161, lazy evaluation of processing mode<br/>
Gregg Kellogg: Another useful thing would be a doc/post about the process to update to 1.1.<br/>
Ivan Herman: We have to clarify that this is not just lazy evaluation, but it is better than just that.<br/>
</details>

**Comment by gkellogg** [comment]
The WG [resolved to close the issue as completed](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-10-18-json-ld#resolution3).
