### ISSUE TITLE
Fix/clarify use of "otherwise" steps in expansion algorithms

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#176]
There are several use of "otherwise" clauses in steps of the Expansion and related algorithms that appears problematic. Some of these seem to be problems introduced by recent modifications to the original algorithms, while others seem to imply an incorrect branch condition (details of some of these below). Please ensure that the conditional language in the algorithms is clear and correct.

In [§4.2.2](https://w3c.github.io/json-ld-api/#algorithm-0), step 7 begins "otherwise", but it follows step 6 which is not a conditional. step 6 was recently added, so perhaps step 7 was meant to relate to a previous condition. Unfortunately, step 5 does not use explicit conditional language, only implying one by way of the assertion ("term MUST NOT be a keyword").

In [§5.1.2](https://w3c.github.io/json-ld-api/#algorithm-3), step 13.4.4 includes the conditional `If expanded property is @id and value is not a string`. By context, I suspect the `otherwise` is not meant to be the negation of this condition, though, but instead act as a new condition like `if expanded property is @id and no error was detected`.

step 13.4.5 is almost identical to step 13.4.4.

Steps 13.4.9, 13.4.11, and 13.4.14 are similar (while 13.4.10 has recently been expanded to avoid this issue by having sub-steps 13.4.10.x).

**Comment by pchampin** [comment]
I agree with your analysis regarding the various "otherwise"''s in [§5.1.2](https://w3c.github.io/json-ld-api/#algorithm-3). Substeps should be introduced, to separate the two parts of the condition, and let the "otherwise" apply to the second part only. I can make a PR for that.

Regarding step 7 of [§4.2.2](https://w3c.github.io/json-ld-api/#algorithm-0), the more I read it, the less I understand it :-/ Let alone the ambiguous "otherwise", I don't see what "removing any `previous definition` from `active context`" means, given that `previous definition` is a local variable, *not* an attribute of `active context`... @gkellogg @dlongley any idea?

**Comment by gkellogg** [comment]
This step has been misplaced, for some reason (mea-culpa). Probably, steps 6 and 7 should be combined and read "Set _previous definition_ to any existing *term definition* for _term_ in _active context_, removing that entry in _active context_."

We need a local copy of _previous definition_ for step 30 to prevent _definition_ from overriding _previous definition_ if it is protected.
