### ISSUE TITLE
FIx Create Term Definition algorithm for terms starting with `@`

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#188]
Based on the recent [resolution to ignore/warn on context terms starting with `@`](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-09-20-json-ld#section5-2), I believe the text in the [Create Term Definition algorithm](https://w3c.github.io/json-ld-api/#algorithm-0), step 5 needs to be updated so that it does *not* indicate that such terms cause processing to be aborted.

**Comment by gkellogg** [comment]
Processing is aborted for that term so that no term definition will be created, which essentially causes them to be ignored. That is the intention.

Perhaps you think that saying "processing is aborted" would be tantamount to rejecting a Promise? That's not what is intended, only the processing of this term.

Perhaps if it said just to return?

**Comment by azaroth42** [comment]
I also interpreted this to be abort completely (e.g. an error). Return would be clearer, IMO.

**Comment by kasei** [comment]
“Return” would be much clearer, given that “ processing is aborted” is the exact same terminology used when an actual error is encountered.
