### ISSUE TITLE
Clarification in algorithms

### ISSUE THREAD

**Issue by pchampin** [w3c/json-ld-api#206]
This is a bunch of minor changes in the algorithms that I think would make them clearer...

Context Processing
* [x]  §4.1 It would be nice to indicate the datatype of each "attribute" of a term definition (especially for implementers using a strongly typed language)
* [x] §4.1 step 2:  the "MUST be a boolean" is confusing, because no error handling is specified here; it would be helpful to add (as a note) that the erreor will be handled later (in step 5.11)
* [x] §4.1 step 5.2.1: _value_ is not defined (should be _context_)
* [x] §4.1 step 5.2.1: it is not not clear what base URI should be used, probably that from _result_?
* [x] §4.1 step 5.6.4: Shouldn't this step be preceded by sometheling similar to 5.2.3?
* [x] §4.1 step 5.6.4: Shouldn't this step be preceded by sometheling similar to 5.2.3?
* [x] §4.1 step 5.13: Shouldn't _override_protected_ be also be passed to create-term-definition?

Create Term Definition
* [x]  §4.2 step 12: if `@protected` is not a boolean, shouldn't this raise an error  (invalid `@protected` value)? NB: it does not exist yet
* [x]  §4.2 step 16.4: only `@context` is checked for an "invalid keyword alias", but the specs also forbids aliasing `@base`, `@container`, `@import`, `@prefix`, `@propagate`, `@protected`, `@version`, `@vocab`.
* [x]  §4.2 step 16.5: the parameters passed to IRI Expansion should be explicit.

IRI Expansion
* [x] §5.2 step 8: it is not clear which *base IRI* is referred to. I'm guessing this is _active_context.base_. What if it is null?

I'll make a PR to that effect this evening (French timezone).

**Comment by gkellogg** [comment]
> §4.1 It would be nice to indicate the datatype of each "attribute" of a term definition (especially for implementers using a strongly typed language)

The syntax document describes the grammar for this, so wouldn't this be a bit repetitive?

> §4.1 step 2: the "MUST be a boolean" is confusing, because no error handling is specified here; it would be helpful to add (as a note) that the erreor will be handled later (in step 5.11)

We can add a note here, but we'll need to anchor 5.11 and potentially have a mis-numbered reference if there are further changes. (Maybe ReSpec should have something like `class=sectionRef` for this).

> §4.1 step 5.2.1: value is not defined (should be context)

👍 

>  §4.1 step 5.2.1: it is not not clear what base URI should be used, probably that from result?

It's the base IRI of the document containing the reference, but we should make that explicit.

> §4.1 step 5.6.4: Shouldn't this step be preceded by sometheling similar to 5.2.3?

Actually, I don't think so, as it will interpret the context differently, but an attempted attack would be caught in 5.2.2.

> §4.1 step 5.13: Shouldn't override_protected be also be passed to create-term-definition?

I don't think it's necessary, as 5.1.1 will fail if there are any protected term definitions.

>  §4.2 step 12: if @protected is not a boolean, shouldn't this raise an error (invalid @protected value)? NB: it does not exist yet

Yes, there should be a test that it is boolean and an error such as "illegal @protected value", otherwise (and, of course, tests).

> §4.2 step 16.4: only @context is checked for an "invalid keyword alias", but the specs also forbids aliasing @base, @container, @import, @prefix, @propagate, @protected, @version, @vocab.

Yes, this should be updated.

>  §4.2 step 16.5: the parameters passed to IRI Expansion should be explicit.

Yes, I find this annoying, but I don't think we can do anything different about it.

> §5.2 step 8: it is not clear which base IRI is referred to. I'm guessing this is active_context.base. What if it is null?

It says "against the _base IRI_ from _active context_", which is consistent with how we refer to members of structured items, such as _active context_. We do this for _term definition_ in §4.1, and say something about the default content of _active context_, which should include _base IRI_.

In general, there is an issue for resolving against a null document base, which is true in all RDF serializations. Typically, every document is expected to have a base IRI, which can cause issues in the distiller and playground. RFC3986 has a whole section on [Establishing a base URI](https://tools.ietf.org/html/rfc3986#section-5.1), which falls back to an application-dependent value; I don't think we need to repeat that here.

I'll do a PR with these changes. I expect to have more from a read-through.

**Comment by gkellogg** [comment]
> §4.2 step 16.4: only @context is checked for an "invalid keyword alias", but the specs also forbids aliasing @base, @container, @import, @Prefix, @propagate, @Protected, @Version, @vocab.

Actually, only `@context` is forbidden to alias; the others could be aliased, but they could never be used. Muddying the message that `@context` can't be aliased so that it can be recognized as a JSON-LD document (along with the necessary chicken/egg issue) is key here. Aliasing `@protected` isn't illegal, but it can't be used. There is a separate statement that keywords used within a context or term definition can't be aliased. If an alias were created, it would expand to it's value, but would raise it's own error in the expansion algorithm.
