### ISSUE TITLE
toRdf test output sorting

### ISSUE THREAD

**Issue by davidlehn** [w3c/json-ld-api#22]
The toRdf n-quads test outputs used to be lexicographically sorted by line, but a handful of newer tests are not.  For instance 0100.  I don't think the spec says anything about this type of ordering?  jsonld.js is having issues with this.  Semantically it shouldn't matter, so what should test runners do to check outputs?  Just sort api result and expected result prior to a compare?  Or did we sort the older results on purpose just to make testing easier?

**Comment by gkellogg** [comment]
The spec says that the result is an RDF Dataset, and the README expects to use RDF Isomorphism (normalization would probably work too). I don’t have a problem with re-ordering the expected results, but I think we’re going to move further from such strictly textual comparisons.

To start to abstract ourselves from specific bnode naming expectations, the README describes a bijectic mapping between produced, and expected bnode identifiers.

**Comment by davidlehn** [comment]
Huh, not sure I'd ever seen that test README before!

I'm not sure what to make of that rdf dataset comparison algorithm.  Seems like a sub-project just to write and test such code for various languages.  I suppose the quicker path is just to run the api result and expected data through rdf-canonize and compare result strings.  Seems heavyweight but would handle all the toRdf issues.  That fromRdf ordering issue looks tricky too.

Maybe the test suite should have some fromRdf and toRdf test cases to specifically stress the test runners ability to handle ordering and blank node naming issues and such.

**Comment by gkellogg** [comment]
> I'm not sure what to make of that rdf dataset comparison algorithm. Seems like a sub-project just to write and test such code for various languages. 

It is the standard way to test RDF processors, because of the bnode naming problem. RDF Dataset Normalization and string compare would do essentially the same thing. Neither are cheep processes, but people specifically working in an RDF environment should already have a solution available. (RDFa chose to use SPARQL ASK, which could do, but it's even more difficult and leaves open other possibility for errors, such as extra statements).

> That fromRdf ordering issue looks tricky too.

Yes, ordering of unordered arrays for comparison sake is a problem, the we just avoided in 1.0, because input statements were always ordered. Arguably, the only real way to test is to do RDF -> JSON-LD -> RDF and the isomorphism/normalization test case, but then you'd miss out proper list encoding, for example. This requires some more thought.

> Maybe the test suite should have some fromRdf and toRdf test cases to specifically stress the test runners ability to handle ordering and blank node naming issues and such.

Personally, I'd like to get rid of the expectation on blank node identifier naming, as it's a weakness IMHO, but makes testing the results more difficult. Probably requires a context-aware comparison mechanism so that it knows how to map blank node identifiers using a bijection, and when to consider arrays as ordered or unordered.

We could consider a service to do this, much like we did for RDFa, but that has it's own issues.
