### ISSUE TITLE
Tests with invalid keyword expect error

### ISSUE THREAD

**Issue by rubensworks** [w3c/json-ld-api#226]
If I'm correct, the resolution of https://github.com/w3c/json-ld-syntax/issues/297 was to ignore (and optionally warn) the use of unknown keywords.

However, toRdf tests tpr38 and tpr39 seem to require an `invalid IRI mapping` error to be thrown. Their description does however mention that such keywords are ignored.

Is this an error in the tests, or is this intentional and am I missing something?

**Comment by gkellogg** [comment]
They are errors (both in toRdf and expansion) not because they have the form of a keyword, but because they do not expand to absolute IRIs. IRI expansion returns `null` and issues a warning when it sees such a keyword, which happens in context processing. Because the value of `@reverse` must expand to an absolute IRI, this is an error.

**Comment by azaroth42** [comment]
No issue, closing.
