### ISSUE TITLE
The propagate option to Create Term Definition is unused.

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-api#233]
It was used previously, but has since been made redundant, the algorithm signature can be simplified.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-12-06-json-ld#section4-1).

- `RESOLVED:  Any changes to algorithm text that do not affect the result of the algorithm may be considered non-normative changes.`
<details><summary><i class="differentiate">View the transcript</i></summary>
4.1. The propagate option to Create Term Definition is unused.<br/>
Benjamin Young: <a href="https://github.com/w3c/json-ld-api/issues/233">https://github.com/w3c/json-ld-api/issues/233</a><br/>
Benjamin Young: first issue is this one …<br/>
… Propagate option is unused in the create term definition.<br/>
Gregg Kellogg: At one time, we passed propagate from context parsing to create term definition. Subsequently we reverted that, so now if you look at the API document, in create term definition, if you click that argument, you’ll see it’s not anywhere in the algorithm<br/>
… I noticed this in the jsonld.js algorithm. Verified in my own implementation<br/>
… so we can simplify it by taking this argument out<br/>
Dave Longley: +1 to remove it and simplify (it doesn’t actually change anything!)<br/>
Gregg Kellogg: question is … is that a normative change?<br/>
… no processing has changed, just the requirements for calling<br/>
… sure that we’ll face other similar things after publication<br/>
Ivan Herman: That means I think that the algorithm doesn’t change, it just has an unnecessary parameter<br/>
Gregg Kellogg: Yes, you’re passing an argument that is never used<br/>
Ivan Herman: So if I remove it, then no change … but it’s definitely borderline<br/>
Dave Longley: in no way would the output of the algorithm change, which is what is normatively defined<br/>
Gregg Kellogg: Yes, that would also speak to making changes to the algorithms in the future … the results can’t change<br/>
Dave Longley: I think this would be a useful precedent to set<br/>
Gregg Kellogg: Sense of the WG is that minor changes to the text in algorithms that do not affect the results, as specified, may be considered editorial changes<br/>
Proposed resolution: Any changes to algorithm text that do not affect the result of the algorithm may be considered non-normative changes. (Dave Longley)<br/>
Rob Sanderson: +1<br/>
Gregg Kellogg: +1<br/>
Dave Longley: +1<br/>
Ivan Herman: +1<br/>
Ruben Taelman: +1<br/>
Benjamin Young: +1<br/>
Tim Cole: +1<br/>
Harold Solbrig: +1<br/>
David I. Lehn: +1<br/>
Gregg Kellogg: +1<br/>
Resolution #3: Any changes to algorithm text that do not affect the result of the algorithm may be considered non-normative changes.<br/>
</details>
