### ISSUE TITLE
Add test for JSON-LD inside a JSON literal.

### ISSUE THREAD

**Issue by davidlehn** [w3c/json-ld-api#237]
Add test, or tests, to ensure JSON literals are not processed as JSON-LD.
This should at least be an expand test that ensures the JSON-LD-in-JSON stays unexpanded.
This was an issue in the jsonld.js implementation.

**Comment by davidlehn** [comment]
Expand #js08 already exists.  @dlongley What additional tests, if any, would be useful here?  Something with a `@context`?

**Comment by dlongley** [comment]
Yes, we should add something with a `@context` that uses a URL. jsonld.js would have previously erroneously resolved it and replaced it inline with the context document.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-12-13-json-ld.html#section4-2).

- `RESOLVED:  Accept test for JSON-LD embedded in JSON to test suite (no editorial action)`
<details><summary><i class="differentiate">View the transcript</i></summary>
JSON-LD featuring JSON featuring JSON-LD test<br/>
Rob Sanderson: <a href="https://github.com/w3c/json-ld-api/issues/237">https://github.com/w3c/json-ld-api/issues/237</a><br/>
David I. Lehn: a literal JSON can contain JSON-LD (e.g. a <code>@context</code> key)<br/>
… we need to make sure that processors do not try to process that<br/>
Rob Sanderson: this is only editorial; the text already says “do not touch this”<br/>
Proposed resolution: Accept test for JSON-LD embedded in JSON to test suite (no editorial action) (Rob Sanderson)<br/>
Rob Sanderson: +1<br/>
David I. Lehn: how should we process such issues?<br/>
Ivan Herman: +1<br/>
Tim Cole: +1<br/>
Ivan Herman: I don’t think we should use meeting time for this<br/>
Harold Solbrig: +1<br/>
David I. Lehn: +1<br/>
Pierre-Antoine Champin: +1<br/>
Resolution #3: Accept test for JSON-LD embedded in JSON to test suite (no editorial action)<br/>
Gregg Kellogg: +1<br/>
Rob Sanderson: but we need to point to a resolution in the PR solving the issue<br/>
</details>

**Comment by davidlehn** [comment]
@gkellogg I don't think the requested test exists yet?  Something with a `@context` in the JSON as @dlongley mentioned above.

**Comment by gkellogg** [comment]
@davidlehn I thought that this issue referred to changes in #238 and #240. Can you create a new PR referencing this issue that does what you indicated?

**Comment by gkellogg** [comment]
This should be solved with #263
