### ISSUE TITLE
Issue with @container arrays

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#242]
[Test t0080](https://w3c.github.io/json-ld-api/tests/expand/0080-in.jsonld) uses a `@container` array value:

`"@container": ["@graph", "@set"]`

The [changelog](https://w3c.github.io/json-ld-api/#changes-since-1-0-recommendation-of-16-january-2014) seems to suggest that this is OK:

> The value for @container in an expanded term definition can also be an array containing any appropriate container keyword along with @set (other than @list). This allows a way to ensure that such entry values will always be expressed in array form.

However, [Create Term Definition](https://w3c.github.io/json-ld-api/#create-term-definition) step 21.1 is not written in a way that supports this combination of container values:

> Initialize container to the value associated with the @container entry, which MUST be either @graph, @id, @index, @language, @list, @set, @type, or an array containing exactly any one of those keywords, an array containing @graph and either @id or @index optionally including @set, or an array containing a combination of @set and any of @index, @id, @type, @language in any order . Otherwise, an invalid container mapping has been detected and processing is aborted.

I read this as indicating that `["@graph", "@set"]` is an invalid container mapping, and processing will be aborted. Is that correct? Can this text and/or the test suite be updated to clarify this?

**Comment by gkellogg** [comment]
No, it is permissible to use `["@graph", "@set"]`, and there are steps in both Compaction and IRI Compaction that take advantage of this. `@graph` should be added to the list of keywords for which `@set` can be used.

**Comment by pchampin** [comment]
Actually the part that says
> containing `@graph` and either `@id` or `@index` optionally including `@set`

does cover that case...

**Comment by pchampin** [comment]
Actually the part that says
> containing `@graph` and either `@id` or `@index` optionally including `@set`

does cover that case...

**Comment by kasei** [comment]
@pchampin how does that cover this case when the container does not contain either @id or @index?

**Comment by pchampin** [comment]
oh, you are right :-/ sorry

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-12-13-json-ld.html#section4-4).

- `RESOLVED:  Update api Create Term Definition step to allow the set of combinations from syntax 9.15.1`
<details><summary><i class="differentiate">View the transcript</i></summary>
4.4. <code>@graph,</code> <code>@set</code><br/>
Rob Sanderson: <a href="https://github.com/w3c/json-ld-api/issues/242">https://github.com/w3c/json-ld-api/issues/242</a><br/>
Rob Sanderson: "<code>@container":</code> ["<code>@graph",</code> "<code>@set"]</code> is used in a test, but the text of the algorithm implies that it is illegal<br/>
Gregg Kellogg: this is an ommision in the algorithm in the list of things allowed with <code>@graph</code><br/>
… the normative section of the syntax does allow this combination<br/>
Gregg Kellogg: <a href="http://localhost:8000/?specStatus=CR&amp;publishDate=2019-12-12#expanded-term-definition">http://localhost:8000/?specStatus=CR&amp;publishDate=2019-12-12#expanded-term-definition</a><br/>
Pierre-Antoine Champin: <a href="https://www.w3.org/TR/json-ld11/#expanded-term-definition">https://www.w3.org/TR/json-ld11/#expanded-term-definition</a><br/>
Rob Sanderson: > If the expanded term definition contains the <code>@container</code> keyword, its value MUST be either <code>@list,</code> <code>@set,</code> <code>@language,</code> <code>@index,</code> <code>@id,</code> <code>@graph,</code> <code>@type,</code> or be null or an array containing exactly any one of those keywords, or a combination of <code>@set</code> and any of <code>@index,</code> <code>@id,</code> <code>@graph,</code> <code>@type,</code> <code>@language</code> in any order<br/>
Rob Sanderson: so the API and Syntax documents are out of sync<br/>
Gregg Kellogg: there was examples specifically added about it<br/>
Proposed resolution: Update api Create Term Definition step to allow the set of combinations from syntax 9.15.1 (Rob Sanderson)<br/>
Gregg Kellogg: +1<br/>
Rob Sanderson: +1<br/>
David I. Lehn: +1<br/>
Ivan Herman: 0<br/>
Tim Cole: +1<br/>
Harold Solbrig: +1<br/>
Benjamin Young: +1<br/>
Pierre-Antoine Champin: +1<br/>
Resolution #5: Update api Create Term Definition step to allow the set of combinations from syntax 9.15.1<br/>
</details>

**Comment by gkellogg** [comment]
@kasei, please let us know if changes in #248 satisfactorily address your concern.

**Comment by kasei** [comment]
Looks good, thanks.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-12-20-json-ld#section5-6).

- `RESOLVED:  Close completed editorial issues API#242, #243, #244, #245, #246`
<details><summary><i class="differentiate">View the transcript</i></summary>
Close editorial issues<br/>
Proposed resolution: Close completed editorial issues API#242, #243, #244, #245, #246 (Rob Sanderson)<br/>
Ruben Taelman: +1<br/>
Gregg Kellogg: +1<br/>
Ivan Herman: +1<br/>
Pierre-Antoine Champin: +1<br/>
Jeff Mixter: +1<br/>
Tim Cole: +1<br/>
Rob Sanderson: +1<br/>
Adam Soroka: +1<br/>
Resolution #9: Close completed editorial issues API#242, #243, #244, #245, #246<br/>
</details>
