### ISSUE TITLE
Duplicated content in Expansion algorithm steps

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#243]
The [Expansion Algorithm](https://w3c.github.io/json-ld-api/#expansion-algorithm) step 13.4.4 includes these two sub-steps:

* 13.4.4.4) Otherwise, set expanded value to the result of using the IRI Expansion algorithm, passing type-scoped context for active context, true for vocab, and true for document relative to expand the value or each of its items. If result already has an entry for @type, prepend the value of @type in result to expanded value, transforming it into an array, if necessary.
* 13.4.4.5) If result already has an entry for @type, prepend the value of @type in result to expanded value, transforming it into an array, if necessary.

The latter step seems to be included in the former step. Given the context of 13.4.4.4, this seems surely to be  accidental.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-12-13-json-ld.html#section4-3).

- `RESOLVED:  remove repeated text from expansion 13.4.4.4`
<details><summary><i class="differentiate">View the transcript</i></summary>
Return of the adding an entry step<br/>
Rob Sanderson: <a href="https://github.com/w3c/json-ld-api/issues/243">https://github.com/w3c/json-ld-api/issues/243</a><br/>
Rob Sanderson: <a href="https://w3c.github.io/json-ld-api/#expansion-algorithm">https://w3c.github.io/json-ld-api/#expansion-algorithm</a><br/>
Rob Sanderson: in the expansion algorithm, step 13.4.4.4 and 13.4.4.5<br/>
… there is the same text repeated<br/>
… looks like a copy-paste error<br/>
Proposed resolution: remove repeated text from expansion 13.4.4.4 (Rob Sanderson)<br/>
Gregg Kellogg: +1<br/>
Harold Solbrig: +1<br/>
Rob Sanderson: +1<br/>
Tim Cole: +1<br/>
David I. Lehn: +1<br/>
Pierre-Antoine Champin: +1<br/>
Benjamin Young: +!<br/>
Benjamin Young: +1<br/>
Resolution #4: remove repeated text from expansion 13.4.4.4<br/>
</details>

**Comment by gkellogg** [comment]
@kasei, please let us know if changes in #249 satisfactorily address your concern.

**Comment by kasei** [comment]
Looks good, thanks.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-12-20-json-ld#section5-6).

- `RESOLVED:  Close completed editorial issues API#242, #243, #244, #245, #246`
<details><summary><i class="differentiate">View the transcript</i></summary>
Close editorial issues<br/>
Proposed resolution: Close completed editorial issues API#242, #243, #244, #245, #246 (Rob Sanderson)<br/>
Ruben Taelman: +1<br/>
Gregg Kellogg: +1<br/>
Ivan Herman: +1<br/>
Pierre-Antoine Champin: +1<br/>
Jeff Mixter: +1<br/>
Tim Cole: +1<br/>
Rob Sanderson: +1<br/>
Adam Soroka: +1<br/>
Resolution #9: Close completed editorial issues API#242, #243, #244, #245, #246<br/>
</details>
