### ISSUE TITLE
XHTML support in HTML script extraction

### ISSUE THREAD

**Issue by ByteEater-pl** [w3c/json-ld-api#244]
The spec contains special handling for text/html resources. Lack of application/xhtml+xml seems an unfortunate omission.

**Comment by gkellogg** [comment]
XHTML is no longer an actively maintained specification (marked superseded now), so is not specifically mentioned. Neither is HTML4. However, JSON-LD should embed just fine in either, although there may be some considerations for how to encode script content.

**Comment by azaroth42** [comment]
Propose close, intentionally omitted.

**Comment by ByteEater-pl** [comment]
> XHTML is no longer an actively maintained specification (marked superseded now), so is not specifically mentioned.
The HTML 5.2 spec contains the IANA registration of the application/xhtml+xml MIME type [1].

> However, JSON-LD should embed just fine in either, although there may be some considerations for how to encode script content.
I was referring to HTML script extraction [2]. The current spec seems to make it work only for content served as text/html and gratuitously not with application/xhtml+xml.

[1] https://www.w3.org/TR/html52/iana.html#application-xhtmlxml
[2] https://www.w3.org/TR/json-ld11-api/#dfn-html-script-extraction

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://github.com/w3c/json-ld-api/issues/244).

- `RESOLVED:  We accept that syntax and api should also refer to XHTML where they refer to text/html`
<details><summary><i class="differentiate">View the transcript</i></summary>
4.1. XHTML vs HTML<br/>
Rob Sanderson: <a href="https://github.com/w3c/json-ld-api/issues/244">https://github.com/w3c/json-ld-api/issues/244</a><br/>
Rob Sanderson: gkellogg objected that XHTML is not an active spec<br/>
… but the author or the issue noted that application/xhtml+xml is one of the content-types specified for HTML 5.2<br/>
Ivan Herman: my initial reaction was the same as gkellogg, but the latest argument is compelling<br/>
Rob Sanderson: <a href="https://www.w3.org/TR/json-ld11-api/#dfn-html-script-extraction">https://www.w3.org/TR/json-ld11-api/#dfn-html-script-extraction</a><br/>
Ivan Herman: but since both content-types are for the same format,<br/>
… all we have to do is add “or ‘application/xhtml+xml’” whenever we mention ‘text/html’<br/>
… Also, epub still refers to XHTML.<br/>
Gregg Kellogg: my concern was that XHTML 1.0 would use different encoding for scripts.<br/>
… If this is just about accepting ‘application/xhtml+xml’ for HTML5, this is not a problem.<br/>
… I would rather not wait on this thing. It is easy to get lost.<br/>
Ivan Herman: if we want to republish something between now and end of CR,<br/>
… this is borderline to substantial change.<br/>
Gregg Kellogg: we will have the same problems with other issues.<br/>
Ivan Herman: many things that will come up are hopefully editorial.<br/>
Rob Sanderson: given the other issues, we will probably want to update the CR.<br/>
… considering this is day 1, and we already have a list of issues and associated PRs.<br/>
Ivan Herman: we are not talking about going back to WD.<br/>
… but we need to go to the director again if we make non-substantial changes.<br/>
Gregg Kellogg: last week we resolved that changes in the text of the algorithms<br/>
… that does not change the result of any test suite,<br/>
Gregg Kellogg: <a href="https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-12-06-json-ld#resolution3">https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-12-06-json-ld#resolution3</a><br/>
Gregg Kellogg: would be considered editorial.<br/>
Rob Sanderson: but surely we were referring the existing test suite<br/>
Gregg Kellogg: dlehn proposed to add new tests, to address some corner cases<br/>
… I thing resolution3 is about “not changing the result of any existing test”<br/>
Proposed resolution: We accept that syntax and api should also refer to XHTML where they refer to text/html (Rob Sanderson)<br/>
Gregg Kellogg: +1<br/>
Ivan Herman: +1<br/>
Rob Sanderson: +1<br/>
Harold Solbrig: +1<br/>
Pierre-Antoine Champin: +1<br/>
David I. Lehn: +1<br/>
Benjamin Young: +1<br/>
Resolution #2: We accept that syntax and api should also refer to XHTML where they refer to text/html<br/>
</details>

**Comment by iherman** [comment]
Reopening this; better to keep it open until the changes are done in the document.

**Comment by gkellogg** [comment]
@ByteEater-pl, please indicate if the change in #250 adequately addresses your concerns.

**Comment by ByteEater-pl** [comment]
It does, thanks.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-12-20-json-ld#section5-6).

- `RESOLVED:  Close completed editorial issues API#242, #243, #244, #245, #246`
<details><summary><i class="differentiate">View the transcript</i></summary>
Close editorial issues<br/>
Proposed resolution: Close completed editorial issues API#242, #243, #244, #245, #246 (Rob Sanderson)<br/>
Ruben Taelman: +1<br/>
Gregg Kellogg: +1<br/>
Ivan Herman: +1<br/>
Pierre-Antoine Champin: +1<br/>
Jeff Mixter: +1<br/>
Tim Cole: +1<br/>
Rob Sanderson: +1<br/>
Adam Soroka: +1<br/>
Resolution #9: Close completed editorial issues API#242, #243, #244, #245, #246<br/>
</details>
