### ISSUE TITLE
Possible problem with Create Term Definition algorithm on compact IRI terms

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#245]
Based on test t0025, I believe that [Create Term Definition](https://w3c.github.io/json-ld-api/#create-term-definition), step 16.5 is wrong.

Processing any term at this point with the syntactic form of a compact IRI will fail with a 'cyclic IRI mapping' error after calling IRI expansion, which then calls (in step 3) Create Term Definition again.

I notice that setting `defined[term]` to true in 16.5 immediately before calling IRI expansion resolves the issue for this particular test, but I do not know what the implications are for possible impact elsewhere in the spec and/or testsuite.

**Comment by gkellogg** [comment]
Looking at my code, it doesn't pass either _local context_ or _defined_ to Create Term Definition and passes the tests, but can potentially lead to a case where term hasn't yet been defined, so your solution would seem to be correct.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-12-13-json-ld.html#section4-6).

- `RESOLVED:  Add to Create Term Definition 16.5 that defined should be set to True, and that it should be resolved as vocabulary relative by adding the appropriate parameter`
<details><summary><i class="differentiate">View the transcript</i></summary>
Create Term Definition 16.5 should set defined?<br/>
Rob Sanderson: <a href="https://github.com/w3c/json-ld-api/issues/245">https://github.com/w3c/json-ld-api/issues/245</a><br/>
Gregg Kellogg: when a term has the form of a CURIE, it is possible that the prefix has not yet been defined<br/>
… so we recursively call “expand IRI”;<br/>
… we keep track of defined terms, this should be updated accordingly<br/>
… also, we should have that it should be resolved against the vocabulary<br/>
Proposed resolution: Add to Create Term Definition 16.5 that defined should be set to True, and that it should be resolved as vocabulary relative by adding the appropriate parameter (Rob Sanderson)<br/>
Gregg Kellogg: +1<br/>
Rob Sanderson: +1<br/>
Benjamin Young: +1<br/>
Pierre-Antoine Champin: +1<br/>
Ivan Herman: +1<br/>
Harold Solbrig: +1<br/>
Tim Cole: +1<br/>
Resolution #7: Add to Create Term Definition 16.5 that defined should be set to True, and that it should be resolved as vocabulary relative by adding the appropriate parameter<br/>
</details>

**Comment by gkellogg** [comment]
@kasei, please let us know if changes in #251 satisfactorily address your concern.

**Comment by kasei** [comment]
Looks good, thanks.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-12-20-json-ld#section5-6).

- `RESOLVED:  Close completed editorial issues API#242, #243, #244, #245, #246`
<details><summary><i class="differentiate">View the transcript</i></summary>
Close editorial issues<br/>
Proposed resolution: Close completed editorial issues API#242, #243, #244, #245, #246 (Rob Sanderson)<br/>
Ruben Taelman: +1<br/>
Gregg Kellogg: +1<br/>
Ivan Herman: +1<br/>
Pierre-Antoine Champin: +1<br/>
Jeff Mixter: +1<br/>
Tim Cole: +1<br/>
Rob Sanderson: +1<br/>
Adam Soroka: +1<br/>
Resolution #9: Close completed editorial issues API#242, #243, #244, #245, #246<br/>
</details>
