### ISSUE TITLE
Issue with type-scoped contexts propagation

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#246]
Test [tc015](https://w3c.github.io/json-ld-api/tests/expand/c015-in.jsonld) tests whether type-scoped contexts propagate by default or not. Based on the language in [syntax document section 1.7](https://www.w3.org/TR/json-ld11/#syntax-tokens-and-keywords), propagate should be false for type-scoped contexts. However, I can't find anywhere in the API document that implements this default for type-scoped contexts.

In [section 4.1.1](https://w3c.github.io/json-ld-api/#overview), there is non-normative text saying:

> If context is not to be propagated, a reference to the previous context is retained so that it may be rolled back when a new node object is entered. By default, all contexts are propagated, other than type-scoped contexts.

However, in 4.1.2, `propagatge` is defaulted to `true` in the algorithm setup, and type-scoped contexts never change this default.

Have I missed something about how propagation is meant to be handled?

**Comment by gkellogg** [comment]
I think 11.2 of the Expansion algorithm should pass `false` for _propagate_, not `true`, as is done in step 11 of the Compaction Algorithm.

Note that the WG resolved that corrections to algorithmic text are not considered to be normative changes if they don't result in any changes to the expected test results.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-12-13-json-ld.html#section4-7).

- `RESOLVED:  Add to Expansion 11.2 that it should pass false for the propagate option for type-scoped contexts`
<details><summary><i class="differentiate">View the transcript</i></summary>
Type-scoped context propagation<br/>
Rob Sanderson: <a href="https://github.com/w3c/json-ld-api/issues/246">https://github.com/w3c/json-ld-api/issues/246</a><br/>
Gregg Kellogg: when a typed-scoped context is encountered,<br/>
… define context is called; the parameters passed to it are wrong<br/>
… the ‘propagate’ parameter should be ‘false’, but the default value ‘true’ is currently used<br/>
… The good news is that we do have tests for this corner case.<br/>
… The intention is clear.<br/>
Proposed resolution: Add to Expansion 11.2 that it should pass false for the propagate option for type-scoped contexts (Rob Sanderson)<br/>
Gregg Kellogg: +1<br/>
Rob Sanderson: +1<br/>
Benjamin Young: +1<br/>
Harold Solbrig: +1<br/>
Pierre-Antoine Champin: +1<br/>
Tim Cole: +1<br/>
Resolution #8: Add to Expansion 11.2 that it should pass false for the propagate option for type-scoped contexts<br/>
Ivan Herman: +1<br/>
</details>

**Comment by gkellogg** [comment]
@kasei, please let us know if changes in #252 satisfactorily address your concern.

**Comment by kasei** [comment]
Looks good, thanks.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-12-20-json-ld#section5-6).

- `RESOLVED:  Close completed editorial issues API#242, #243, #244, #245, #246`
<details><summary><i class="differentiate">View the transcript</i></summary>
Close editorial issues<br/>
Proposed resolution: Close completed editorial issues API#242, #243, #244, #245, #246 (Rob Sanderson)<br/>
Ruben Taelman: +1<br/>
Gregg Kellogg: +1<br/>
Ivan Herman: +1<br/>
Pierre-Antoine Champin: +1<br/>
Jeff Mixter: +1<br/>
Tim Cole: +1<br/>
Rob Sanderson: +1<br/>
Adam Soroka: +1<br/>
Resolution #9: Close completed editorial issues API#242, #243, #244, #245, #246<br/>
</details>
