### ISSUE TITLE
Markup missing for variable in Create Term Definition

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#260]
Markup is missing from [Create Term Definition](https://w3c.github.io/json-ld-api/#create-term-definition) step 28 for `value` to indicate it as a variable.

**Comment by gkellogg** [comment]
We say "the value" and not "_value_", but it probably should be consistent with the previous steps.

Note that, other than the removal of "the", this is purely formatting. The clickable nature of variables is only true for the ED, not anything that's published, so it is a simple formatting change, and marking it as a change since CR would be excessive, IMO.

**Comment by kasei** [comment]
> The clickable nature of variables is only true for the ED, not anything that's published, so it is a simple formatting change, and marking it as a change since CR would be excessive, IMO.

Understood. However, I'm *very* saddened to hear that the clickable variables will not make it through to the REC documents. As a point of feedback on implementing JSON-LD purely from the spec document, I can't imagine having gotten through it without the clickable variables. If there is *any* way to get this feature into the publishing process leading to the REC docs, *please* consider doing it.

**Comment by gkellogg** [comment]
I agree, but the ReSpec folks have their reasons, based upon their interpretation of W3C norms. You might raise an issue there for clarification.

Of course, we have some other active aspect to our specs which don’t seem to be an issue, so I would support a change to ReSpec to keep this when publishing.

**Comment by kasei** [comment]
OK, thanks. I'll look into raising an issue there, or discussing with @azaroth42 about pushing for a change.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-12-20-json-ld#section5-4).

- `RESOLVED:  Add formatting to create term def step 28 (no entry in changelog as the /text/ doesn’t change)`
<details><summary><i class="differentiate">View the transcript</i></summary>
Missing markup in step 28<br/>
Rob Sanderson: <a href="https://github.com/w3c/json-ld-api/issues/260">https://github.com/w3c/json-ld-api/issues/260</a><br/>
Rob Sanderson: This next issue is also very editorial.<br/>
… The value in the linked step has no markup.<br/>
Gregg Kellogg: The formatting that allows you to click on it, and see other usages, is only available on GitHub, and will go away once we go to Rec.<br/>
… It would be good to look into making this survive the transition.<br/>
Proposed resolution: Add formatting to create term def step 28 (no entry in changelog as the /text/ doesn’t change) (Rob Sanderson)<br/>
Gregg Kellogg: +1<br/>
Rob Sanderson: +1<br/>
Jeff Mixter: +1<br/>
Ruben Taelman: +1<br/>
Tim Cole: +1<br/>
Pierre-Antoine Champin: +1<br/>
Adam Soroka: +1<br/>
Resolution #7: Add formatting to create term def step 28 (no entry in changelog as the /text/ doesn’t change)<br/>
</details>
