### ISSUE TITLE
Incomplete conditional when determining error case in Create Term Definition

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#261]
[Create Term Definition](https://w3c.github.io/json-ld-api/#create-term-definition) step 28 says:

> If the value contains any entry other than `@id`, `@reverse`, `@container`, `@context`, `@language`, `@nest`, `@prefix`, or `@type`, an invalid term definition error has been detected and processing is aborted.

I believe this list is missing several valid values:

* `@direction`, as step 25 uses this as a key:

> If value contains the entry `@direction` and does not contain the entry `@type`

* `@protected`, as step 11 uses this as a key:

> If the `@protected` entry in value is true set the protected flag in definition to true.

* `@index`, as step 22 uses this as a key:

> If value contains the entry `@index`

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-12-20-json-ld#section5-2).

- `RESOLVED:  Agree missing keywords in step 28, accept pchampin’s PR #267, and close`
<details><summary><i class="differentiate">View the transcript</i></summary>
<code>@direction</code> etc missing in step 28<br/>
Rob Sanderson: <a href="https://github.com/w3c/json-ld-api/issues/261">https://github.com/w3c/json-ld-api/issues/261</a><br/>
Rob Sanderson: This issue is more extensive.<br/>
… The Create Term Definition lists a few keywords, but some are missing.<br/>
… pchampin also has a PR for this.<br/>
Proposed resolution: Agree missing keywords in step 28, accept pchampin’s PR #267, and close (Rob Sanderson)<br/>
Gregg Kellogg: +1<br/>
Rob Sanderson: +1<br/>
Ruben Taelman: +1<br/>
Tim Cole: +1<br/>
Jeff Mixter: +1<br/>
Pierre-Antoine Champin: +1<br/>
Resolution #5: Agree missing keywords in step 28, accept pchampin’s PR #267, and close<br/>
</details>

**Comment by gkellogg** [comment]
@kasei changes made, please acknowledge resolution.

**Comment by kasei** [comment]
@gkellogg yes, looks good. Thanks.
