### ISSUE TITLE
Problem testing non-expanded value in Expansion algorithm 13.4.7.1

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#269]
[Expansion Algorithm](https://w3c.github.io/json-ld-api/#expansion-algorithm) step 13.4.7.1 says:

> If `input type` is `@json`, set `expanded value` to `value`. If `processing mode` is `json-ld-1.0`, an `invalid value object value` error has been detected and processing is aborted.

I believe the initial test in this step should be against the *expansion* of `input type`. Test [tjs16](https://w3c.github.io/json-ld-api/tests/expand-manifest.html#tjs16) demonstrates this by using a key `json` that maps to `@json`.

**Comment by gkellogg** [comment]
@kasei, text is updated in PR #275 to use the IRI Expansion algorithm to get the result for comparison. Please indicate if this solves the issue.

**Comment by kasei** [comment]
@gkellogg I do not understand the updated text in #275. Ignoring the trailing error handling text, it now reads:

> If `input type` is not `null`, it was determined in step 12 that element is a value object representing a JSON literal. Set `expanded value` to `value`.

Is "it was determined in step 12 that element is a value object representing a JSON literal" meant to be a note, or a conjunctive clause? If the former, I think it needs note styling. If the latter, I'm confused by both the trailing period (should it be a comma?) and the removal of the explicit mention of the `@json` test (which is now neither mentioned in 13.4.7.1 or in 12).

**Comment by gkellogg** [comment]
It is descriptive, and if removed, would not change the meaning. It could be a note, or an inline clause. The trailing period should probably, instead, but a semi-colon.

The removal of mentioning `@json`, is because, as indicated, in step 12, _input type_ will only be set to a non-null value if it is an `@type` who's value expands to `@json`, so a further test is redundant. We could have changed step 12 to not predicate setting _input type_ on it's being `@json`, but then would potentially need to record both an _expanded input type_ and _input type_ (the original unexpanded value), and it's not used anywhere else in the algorithm. Rather than re-write that, it seemed simpler to just look to see if _input type_ is not null.

We could consider renaming _input type_ to something like _type is json_.

**Comment by kasei** [comment]
@gkellogg, It's not obvious to me based on the text of 12 why "input type will only be set to a non-null value if it is an @type who's value expands to @json." I don't see any reference to JSON in step 12. Can you help me understand this? Is this just something that falls out of the spec as a whole that isn't explicit in the text of step 12?

**Comment by gkellogg** [comment]
No, I was mis-reading it before, for some reason. I think we can change the language for establishing _input type_ to set it to the expanded value. Note that we avoid a bunch of discussion on how to actually expand either the entry or its value. We could probably solve this by combining them together as follow:

> Initialize _input type_ to the **expansion of the** last value of the first entry in _element_ expanding to `@type` (if any), ordering entries lexicographically by key. **Both entry key and value are expanded using the IRI Expansion algorithm, passing _active context_ and `true` for _vocab_.**

Step 13.4.7.1 then reverts to checking if _input type_ is `@json`.

Step 13.4.16 would then be "Unless _expanded value_ is `null`, and _expanded property_ is @value, and _input type_ is not `@json`, set the _expanded property_ entry of _result_to _expanded value_."

This would through way null values of `@value`, unless _input type_ is `@json`, which allows `null` to be used as a JSON literal.

**Comment by gkellogg** [comment]
Updated PR #275 to use that language, brining it closer to the original.

**Comment by kasei** [comment]
@gkellogg changes look good, thanks!
