### ISSUE TITLE
Addition of note about rdf:JSON value space comparison

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#306]
The [JSON-LD Test Suite](https://w3c.github.io/json-ld-api/tests/) discussion of toRdf tests says:

> The expected results can be compared using RDF Dataset Isomorphism.

Should this explicitly mention that the `rdf:JSON` datatype must be supported when comparing RDF Datasets? As this is a new datatype, existing code to perform Dataset comparison may not currently support rdf:JSON value-space comparisons.

**Comment by gkellogg** [comment]
The JSON canonicalization is part of JSON-LD when creating the literal. As part of the RDF Abstract Syntax the lexical form is in canonical form. There should be no requirement for other serializations to do anything with this, and values can be compared as strings, as long as the match the rdf:JSON datatype.

It is because JSON-LD uses an internal representation that JCS comes into play when creating the literal. Certainly, if other syntaxes were to support a native JSON representation, then canonicalization would come into play.

**Comment by kasei** [comment]
@gkellogg –

[Data Round Tripping](https://w3c.github.io/json-ld-api/#data-round-tripping) says:

> The canonical lexical form of a JSON literal value is non-normative, as a normative recommendation for JSON canonicalization is not yet defined. Implementations SHOULD use the following guidelines when creating the lexical representation of a JSON literal...

If this is non-normative *and* a canonical form doesn't exist, how can the tests rely on values being canonical? The ISSUE note in [Object to RDF Conversion](https://w3c.github.io/json-ld-api/#algorithm-13) reads to me like the tests cannot assume a canonical lexical representation.

**Comment by gkellogg** [comment]
The tests README/index should say that the non-normative algorithm needs to be used for isomorphism checks to work.

We would have liked to make it normative, but IETF isn't there yet.

**Comment by kasei** [comment]
Could you also please add an `option` in the toRdf-manifest.jsonld file to indicate in a machine-readable way that such a requirement is in place for these tests?

**Comment by gkellogg** [comment]
@kasei I added descriptions and the _useJCS_ option to affected tests. in PR #308.

**Comment by gkellogg** [comment]
This was discussed [in a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2020/2020-01-10-json-ld.html#section3-2) and we agreed that this is resolved.
