### ISSUE TITLE
Ambiguous conditional language used in Compaction 3.3

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#334]
[Compaction](https://w3c.github.io/json-ld-api/#algorithm-6) step 3.3 says:

> If `result` contains only one item (it has a length of 1), `active property` is not `@graph` or `@set`, or the container mapping for `active property` in `active context` does not include `@list` or `@set`, and `compactArrays` is `true`, set `result` to its only item.

I find the language here to be indecipherable. Based on some of the tests, my best guess is that the intention is something like:

```
If
	(
		(
			(`result` contains only one item (it has a length of 1))
			AND
			(`active property` is neither `@graph` nor `@set`)
		)
		OR
		(
			(the container mapping for `active property` in `active context` does not include `@list` or `@set`)
			AND
			(`compactArrays` is `true`)
		)
	)
```

Is that the intended semantics? Either way, could this language be clarified?

**Comment by gkellogg** [comment]
It should be `result.length == 1 && compactArrays && ((active property is not either '@graph' or '@set') or (the container mapping of active property does not include either '@list' or '@set'))`

Perhaps it's best to split it into multiple clauses.

1) If _result_ contains more than one value or active property is either `@graph` or `@set`, return _result_.
2) Otherwise, if the container mapping for _active property_ in _active context_ includes either `@list` or `@set`, return _result_.
3) Otherwise, return the first value in _result_.

**Comment by gkellogg** [comment]
@kasei The change in PR #341 should make this simpler to parse.
