### ISSUE TITLE
Normalize language tag component of i18n datatype IRI?

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#337]
[Object to RDF Conversion](https://w3c.github.io/json-ld-api/#algorithm-13) step 13.2 constructs a datatype IRI based on language and direction:

> If `rdfDirection` is `i18n-datatype`, set `datatype` to the result of appending `language` and the value of `@direction` in `item` separated by an underscore ("_") to `https://www.w3.org/ns/i18n#`. Initialize `literal` as an RDF literal using `value` and `datatype`.

While there is "MAY" normative text about normalizing language tags, there doesn't seem to be any text about normalizing the language tag values when included in a datatype IRI like this. Test [tdi10](https://w3c.github.io/json-ld-api/tests/toRdf-manifest.html#tdi10) seems to assume the value is normalized in lowercase. Moreover, I would think that *not* normalizing could cause lots of trouble with unexpected data (e.g. two literals that differ only in the case of the language tag component of this datatype IRI; *shouldn't* such literals have the same value?).

**Comment by gkellogg** [comment]
This as introduced in #167, but I don't think we discussed anything specifically about continuing to do the lower-case normalization when creating the i18n datatype, which makes sense. @iherman do you remember discussing this?

**Comment by iherman** [comment]
@gkellogg right, I do not think we discussed this. That being said, normalizing for the purpose of the URI handling does make sense imho. For the sake of consistency, we should follow the same rules as in #167.

We have to realize, however, that the language tags have a tradition that is more complex than that. AFAIK, they usually write 'en-US' instead of 'en-us'. The rules in #167 leave that intact, they just say that the tag must be valid, and we should probably say the same thing for this datatype.

Which does mean that the datatype comparison cannot be character by character but, instead, based on a regex. Ugly, but that is the world we live in:-)

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2020/2020-01-24-json-ld.html#section3-1).

- `RESOLVED:  In toRDF recommend normalization of language tag based URIs`
- `RESOLVED:  … also compound literal form`
<details><summary><i class="differentiate">View the transcript</i></summary>
3.1. Normalize language tags<br/>
<b>link:</b> <a href="https://github.com/w3c/json-ld-api/issues/337">https://github.com/w3c/json-ld-api/issues/337</a><br/>
Rob Sanderson: This is about our workaround language tags in i18n namespace.<br/>
Gregg Kellogg: We removed requirements to normalize language tags to lowercase, because it is problematic for many people in i18n community. When creating RDF, we have possibility that 2 processors create different data types.<br/>
… The question is if that is what we intended. To allow 2 diff datatypes by 2 different processors.<br/>
Ivan Herman: That would be wrong in terms of RDF.<br/>
… If you have 2 datatypes with different cases, RDF sees those as not equal.<br/>
… Maybe pchampin_ will say I’m wrong…<br/>
Pierre-Antoine Champin: I slightly disagree. 2 different URLs may denote different things, but also the same, but this depends on implementation.<br/>
… It’s hard to require all impls to support these different i18n datatypes and consider them equal.<br/>
… We could say that they are semantically equivalent.<br/>
Ivan Herman: Yes, we can do that. I don’t know if we are discussing something that is insignificant.<br/>
… If we do that, and have an implementation that does datatype reasoning, then that impl will likely fall on its face.<br/>
… Datatype reasoning is quite a challenge. Many implementations just check char-by-char.<br/>
… We could say that if you use these datatypes, that you are supposed to lowercase language tags.<br/>
… It’s ugly, but I don’t see a better choice.<br/>
Rob Sanderson: Is there some i18n requirement?<br/>
Ivan Herman: No, it’s a habit that there is mixing of cases.<br/>
… Usual way is:<br/>
Ivan Herman: the usual way is : en-US and not en-us<br/>
Ivan Herman: We should not require normalization when using lang tags the old way, but we should when using i18n datatypes.<br/>
Rob Sanderson: Is the set of characters that is permissible in URIs and language tags compatible?<br/>
Ivan Herman: Just ASCII characters.<br/>
Pierre-Antoine Champin: There will be 2 kinds of RDF impls: ones not recognizing our custom IRIs, and those that do.<br/>
… Those that will take into account our custom datatypes, can interpret them as lang tags and do smart things.<br/>
… The roundtripping would be lost when direction is used. I’m still in favour of not normalizing them.<br/>
Gregg Kellogg: I’m neutral on normalization. We should add a non-normative note in any case.<br/>
Dave Longley: Was it a mistake to not normalize language tags when they were invented?<br/>
Ivan Herman: Invented by whom?<br/>
Dave Longley: Not JSON-LD, but the group that came up with it 30 years ago…<br/>
Ivan Herman: We can not change it because it’s out there already.<br/>
Rob Sanderson: We can fix it for reduced datatype IRI.<br/>
Dave Longley: It looks like this grew organically, so the spec was built around it.<br/>
… What we introduce is new, so we can enforce normalization.<br/>
… So we simplify part of the space.<br/>
Ivan Herman: I don’t disagree.<br/>
… How important is it to roundtrip on such a detail?<br/>
… Because that is why we are discussing this.<br/>
… I don’t think it’s important.<br/>
… So I would normalize it.<br/>
Gregg Kellogg: From RDF Concepts: “A literal is a language-tagged string if the third element is present. Lexical representations of language tags may be converted to lower case. The value space of language tags is always in lower case.”<br/>
Gregg Kellogg: We did change the language of JSON-LD, which always normalized language tags, which was over-strict.<br/>
… RDF spec says that language tags may be lowercased.<br/>
… We are talking here about special case: roundtripping.<br/>
… It’s a minor thing what we are going to do.<br/>
… I would support that we change the language in toRdf, that language tags be normalized in compound literals and i18n.<br/>
Rob Sanderson: We ran into this in practice when having to do case-insensitive language tag comparison.<br/>
Proposed resolution: In toRDF recommend normalization of language tag based URIs (Rob Sanderson)<br/>
Pierre-Antoine Champin: +1<br/>
Rob Sanderson: +1<br/>
Ivan Herman: +1<br/>
Benjamin Young: +0<br/>
Gregg Kellogg: +1<br/>
Dave Longley: +1<br/>
Ruben Taelman: +1<br/>
Harold Solbrig: +0<br/>
David I. Lehn: +1<br/>
Adam Soroka: +1<br/>
Resolution #2: In toRDF recommend normalization of language tag based URIs<br/>
Proposed resolution: … also compound literal form (Rob Sanderson)<br/>
Rob Sanderson: +1<br/>
Pierre-Antoine Champin: +1<br/>
Ruben Taelman: +1<br/>
Dave Longley: +1<br/>
Gregg Kellogg: +1<br/>
Adam Soroka: +1<br/>
Resolution #3: … also compound literal form<br/>
Ivan Herman: +1<br/>
David I. Lehn: +1<br/>
Benjamin Young: +1<br/>
</details>

**Comment by gkellogg** [comment]
@kasei (and @himorin), the algorithm was updated in PR #363 to normalize language tags when creating i18n literals or compound objects. Note that these operations are non-normative.

**Comment by kasei** [comment]
@gkellogg Looks good, though I'm not sure what you mean by "these operations are non-normative." Nothing in #363 suggests non-normative operations, does it? If it *is* non-normative, are there any tests that should be marked as requiring this normalization to pass?

**Comment by gkellogg** [comment]
The syntax document describes both i18n datatypes and compound literals as experimental and non-normative. The algorithms condition this behavior on the `rdfDirection` option, which defaults to `null`. The tests which use this are marked using the `rdfDirection` option. We don't really have a way of describing tests as being non-normative themselves.

**Comment by gkellogg** [comment]
Note that toRdf/di10 and toRdf/di12 require this normalization (but need updates).

**Comment by kasei** [comment]
FWIW, tests like this in SPARQL use new values asserted for the `mf:requires` predicate. That was enough to indicate that you could be conformant without passing those tests if you didn't support the named feature.

**Comment by gkellogg** [comment]
Yes, adding something like `mf:requires` might be a good idea for this and some other cases such as HTML content extraction.
