### ISSUE TITLE
typo and question

### ISSUE THREAD

**Issue by roptat** [w3c/json-ld-api#364]
Hi,

not sure how to fix it properly: 13.4.8.1 and 13.4.9 say "MAY be an empty map or an array of zero or strings."

is it "an array of zero strings" or "an array of zero or more strings"?

Also, it's not the first time I encounter this wording. Does this mean my implementation needs to ensure it's either a string or frame expansion is set and it's either an empty map or an array of strings? Or is this part optional?

**Comment by gkellogg** [comment]
Yes, should be "array of zero **or more** strings".

Frames have a different syntax, and can use `{}` or an array for things like `@id`, where it would otherwise be illegal. In such case, it could be a string, an empty object, an empty array, or an array of one or more strings. The empty object case is a wild card, and the empty array means that there should be no such property. See [Frame Matching Algorithm](https://w3c.github.io/json-ld-framing/#frame-matching).
