### ISSUE TITLE
Unclear how to set original base URL in Context Processing

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#370]
(Related to #265, #356)

[Context Processing Overview](https://w3c.github.io/json-ld-api/#overview) 4.1.1 says:

> When an  active context  is initialized, the value of the  original base URL  is initialized from the original  `documentUrl`  of the document containing the initial  context . This is necessary when resetting the  active context  by setting it to  null  to retain the original default  base  IRI .

What about when there is no `documentUrl`? Is it `null`, or is it the current base IRI? The `documentUrl` field is only relevant when the LoadDocumentCallback has been used.

This also impacts `compact()` step 3, and `expand()` step 4.

**Comment by gkellogg** [comment]
This is not dissimilar from Turtle serialization from a form, rather than a remote document. Also, the JSON-LD Playground. Implementations provide a reasonable default to use as a document base.

Perhaps if step 7 of the `expand()` API definition provided for the case where there is no remote document having a documentUrl. But, really, the use of a relative URL to locate a context from a form is non-sensical. Maybe step 5.2.1 should generate an error if _context_ does not result in a valid IRI after resolution. Perhaps `invalid IRI mapping` could be used for this case too.

**Comment by gkellogg** [comment]
Actually, the LoadDocumentCallback will generate a "loading document failed" error if the URL can't be resolved, so no new error detection is required.

I did add changes to the `expand()` API definition to fallback to `JsonLdOptions/base` if there is no `documentUrl`, which is how it's typically handled in form-based parsers. Implementations may provide a default for this, but we don't need to describe that non-normative behavior.

**Comment by gkellogg** [comment]
@kasei see pending change in #377.

**Comment by kasei** [comment]
@gkellogg I think the changes to `expand()` in #377 are good, but the description in 4.1.1 is still misleading as in some cases there will simply not be a relevant `documntUrl`.

**Comment by gkellogg** [comment]
Updated in 50a50ca0, and to give `base` a default of `null`.

**Comment by gkellogg** [comment]
Updated in #377.
