### ISSUE TITLE
No default value defined for base URL in Create Term Definition

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#375]
(Related to #265, #356)

[Create Term Definition](https://w3c.github.io/json-ld-api/#algorithm-0) says that `base URL` is an optional input variable, but does not define a default value. It is then used unconditionally in step 21.3 and 21.4.

**Comment by gkellogg** [comment]
I'll check, but I believe that the only times that _base URL_ would be used in Create Term Definition it is passed as an option.

**Comment by kasei** [comment]
Then I'd suggest adding language for a default value of `null`.

**Comment by gkellogg** [comment]
Updated in #377.

**Comment by kasei** [comment]
@gkellogg I don't see any change in #377 to the text about default values for the optional arguments in Create Term Definition. Am I missing something?

**Comment by gkellogg** [comment]
See the [JsonLdOptions dictionary](https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/377.html#the-jsonldoptions-type) definition for initializers.

**Comment by kasei** [comment]
How is that relevant? This is about a named, optional argument to Create Term Definition, not about a field in a JsonLdOptions structure. Right?

**Comment by gkellogg** [comment]
Step 4 of `expand()` uses `documentUrl`, if it is available, otherwise the `base` option from _options_. As described for that parameter, default values (e.g., for `base`) are defined in [JsonLdOptions](https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/377.html#dom-jsonldoptions).

It should be the case that when the API calls the Context Processing algorithm that the _base IRI_ and _original base URL_ options will always be set from one of these. There's code in the Context Processing algorithm to check if both _context_ and _base IRI_ aren't valid IRIs.

**Comment by kasei** [comment]
I'm lost. I still see Create Term Definition saying `base URL` is optional, and not providing a default value. And then using that value unconditionally. `expand()` is not the only place that Create Term Definition is invoked, so I don't think changes there can resolve this issue entirely.

For example, IRI Expansion 6.3 invokes Create Term Definition without a base URL argument. Now, it *may* be possible that this invocation cannot reach Create Term Definition 21.3, but that's not obvious to me, which is why I'm concerned about such use of an undefined value.

**Comment by gkellogg** [comment]
So, Create Term Definition is always called with the base URL argument. In Step 5 of `expand()` it is called with  _original base URL_ from _active context_ established in step 4. In Step 6, it is called with the _contextUrl_ from the header, which per HTTP will be an absolute URL.

In Step 4, _original base URL_ is established either from the _documentUrl_ of the remote document, or the _base_ option, which is initialized to `null` in JsonLdOptions, if not set otherwise.

The Create Term Definition algorithm says that the default for _base URL_ is `false`, but it should be `null`. I'll update that. But, those calls should probably use the _base URL_ definition from the associated term in the context which is being passed.

**Comment by kasei** [comment]
> So, Create Term Definition is always called with the base URL argument.

This is not true. Please see the example I just included above.

> The optional inputs are base URL, protected which defaults to false, and override protected, defaulting to false, which is used to allow changes to protected terms..

I did not read this as providing a default value for `base URL` (since there are three arguments discussed, and two default values).

**Comment by gkellogg** [comment]
Yes, I misread that; it does now. It's also not necessary to pass a _base URL_ from those places in Create Term Definition, as the default `null` value will suffice. (There could be a corner-case when expanding `@type` values when creating terms, if those `@type` values have embedded contexts, but those will be picked up when going back to the original term definition.)

**Comment by kasei** [comment]
d78d8d2 looks good. Thanks.
