### ISSUE TITLE
Unclear usage of `active property` in the Expansion Algorithm

### ISSUE THREAD

**Issue by timothee-haudebourg** [w3c/json-ld-api#428]
I have some misunderstandings on the usage of the input variable `active property` in the Expansion Algorithm.

- The variable `active property` is noted as required. However in step 4.1, 13.4.11.1 and 19, it is mentioned that its value might be `null`. It is unclear when, where and why the Expansion Algorithm can be called with a null active property. It should be clear at the beginning that this variable may be nullified. Moreover it seems to be used multiple times in the algorithm with the assumption of not being `null` (for instance step 5.2.2). This should be clarified.

- Even if it is not `null`, it is assumed for instance step 4.2 that it has an associated term definition in `active context`. It is not obvious that it is the case, and nothing is specified for the case where such term definition does not exist.

- I have not seen in section 5 what should be the initial value of `active property` when the goal is simply to expand a given JSON-LD document. Should it be `null`?

**Comment by gkellogg** [comment]
> I have some misunderstandings on the usage of the input variable `active property` in the Expansion Algorithm.
> 
> * The variable `active property` is noted as required. However in step 4.1, 13.4.11.1 and 19, it is mentioned that its value might be `null`. It is unclear when, where and why the Expansion Algorithm can be called with a null active property. It should be clear at the beginning that this variable may be nullified.

On the first call from the API [expand()](https://w3c.github.io/json-ld-api/#dom-jsonldprocessor-expand) method, the Expansion algorithm is called with a `null` value for _active property_, as indeed, there is no current property.

> Moreover it seems to be used multiple times in the algorithm with the assumption of not being `null` (for instance step 5.2.2). This should be clarified.

In 5.2.2, it's sort of like saying "If the _container mapping_ of `null` includes `@list`, and there is clearly no such term definition. But, the language could be more explicit (including that the _container mapping_ comes from a term definition associated with _active property_, if not `null`.

> * Even if it is not `null`, it is assumed for instance step 4.2 that it has an associated term definition in `active context`. It is not obvious that it is the case, and nothing is specified for the case where such term definition does not exist.

In 4.2, there would be no term definition for `null`. We can be explicit to look for a term definition only if _active property_ is not `null`, which is more correct, but definitely more verbose.

> * I have not seen in section 5 what should be the initial value of `active property` when the goal is simply to expand a given JSON-LD document. Should it be `null`?

See note above on [expand()](https://w3c.github.io/json-ld-api/#dom-jsonldprocessor-expand) step 8. All API methods will end up going through this step.

**Comment by timothee-haudebourg** [comment]
Thanks for the clarification, I was definitely missing the infos of the `expand()` method. I still think it is a bit confusing not to have the precise domain of each input variable clearly stated at the beginning of the algorithms, but I guess we have enough infos to deduce it.

Last question: when it is required to use "`base URL` from the term definition for `active property` in `active context`" (for instance step 4.2 or 8), it is not specified what happens if such term definition does not exist. If I understand the idea, we should use `null` as `base URL` in this case, right?

**Comment by timothee-haudebourg** [comment]
Well I don't think the Context Processing Algorithms can take a `null` base URL so I'm a bit lost here.

**Comment by gkellogg** [comment]
> Last question: when it is required to use "`base URL` from the term definition for `active property` in `active context`" (for instance step 4.2 or 8), it is not specified what happens if such term definition does not exist. If I understand the idea, we should use `null` as `base URL` in this case, right?

`base URL` is a property of an _active context_, not a term definition. It is used when expanding document-relative IRIs as described in [IRI Expansion](https://w3c.github.io/json-ld-api/#iri-expansion) when _document relative_ is `true`.

`base URL` will default from the API `base` option, the document location, or the vale of `@base` in a (non-remote) context. There is a case when extracting from HTML, where the `html>head>base>@href` can be used instead, which can interact with these, but there's really only one test that triggers it.

Of course, it is possible that base will end up being `null`, which would mean that you can't turn relative IRIs into absolute IRIs. Normally, this isn't an issue, but it will prevent RDF Triples from being emitted if it contains any non-resolved relative IRIs. This would most likely happen when using the API without the `base` option and where the input is text, rather than a URL.

> Well I don't think the Context Processing Algorithms can take a null base URL so I'm a bit lost here.

Well, `@base` can be `null` in a context, which would have the affect of rolling back to either the document location or `base` option. The algorithms can take `null`; while we don't specifically call this out in IRI Expansion, resolving a relative IRI against `null` would naturally lead to the original unresolved IRI, which is invalid, but largely ignored in the algorithms.

**Comment by timothee-haudebourg** [comment]
Thanks for taking the time to answer my questions again :)
However I'm not sure to follow the first part of your response.

> `base URL` is a property of an active context, not a term definition

Well according to [section 4.1](https://www.w3.org/TR/json-ld11-api/#context-processing-algorithm), `base URL` **is** a property of a term definition. There is also an `original base URL` from active context, however in the sentence quoted from step 4.2 of the Expansion Algorithm...

> If property-scoped context is defined, set active context to the result of the Context Processing algorithm, passing active context, property-scoped context as local context, and base URL **from the term definition** for active property in active context

...I read that it refers to the `base URL` of a term definition.

> which is invalid, but largely ignored in the algorithms.

This makes me feel like there is a lot of implicits, which scares me a little. Maybe it would be nice to at least give the domain of each variable at the beginning of the algorithms so to have a bit more visibility on what's ahead.

**Comment by gkellogg** [comment]
> Thanks for taking the time to answer my questions again :)
> However I'm not sure to follow the first part of your response.
> 
> > `base URL` is a property of an active context, not a term definition
> 
> Well according to [section 4.1](https://www.w3.org/TR/json-ld11-api/#context-processing-algorithm), `base URL` **is** a property of a term definition. There is also an `original base URL` from active context, however in the sentence quoted from step 4.2 of the Expansion Algorithm...

Ahh, yes this was a relatively recent addition to be more explicit about how to resolve relative references to context files; the previous text was more hand-wavy.

In step 5.13 of Context Processing, the _base URL_ passed in as an argument is passed on to the Create Term Definition algorithm so that it can be saved in the term definition and later used when instantiating a new active context. This is necessary, as different term definitions in the active context could come from contexts loaded from different URLs.

> > If property-scoped context is defined, set active context to the result of the Context Processing algorithm, passing active context, property-scoped context as local context, and base URL **from the term definition** for active property in active context
> 
> ...I read that it refers to the `base URL` of a term definition.

Yes, this is so that a property-scoped (or type-scoped) context which was a relative URL can be resolved relative the the location of the context in which the term was defined.

Note that implementations do not need to follow the spec exactly, and another solution wold be to resolve all relative context URLs when the containing term definition is originally defined. The key is to reproduce the same results.

> > which is invalid, but largely ignored in the algorithms.
> 
> This makes me feel like there is a lot of implicits, which scares me a little. Maybe it would be nice to at least give the domain of each variable at the beginning of the algorithms so to have a bit more visibility on what's ahead.

It's probably a bit late in the process to update the description of each input with its relevant range.

**Comment by gkellogg** [comment]
This was discussed in a [meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2020/2020-04-03-json-ld#resolution1) and the group [resolved](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2020/2020-04-03-json-ld#resolution1) to close the issue as wont fix.
