### ISSUE TITLE
compacting types with mode 1.0

### ISSUE THREAD

**Issue by roptat** [w3c/json-ld-api#437]
Test 0106 is entitled "Ensures that a single @type value is not represented as an array in 1.0". However, my implementation returns the type as an array with one element in this test.

First of all, the expansion algorithm already returns an array in that case, because of step 16 of the expansion algorithm. Skipping that step when processing mode is 1.0 doesn't trigger any test failure.

Then, when compacting a type in 12.2, as array is set to true, because type's container mapping contains `@set`, so the result is an array, whether or not the expansion gave a string or an array.

**Comment by gkellogg** [comment]
In 1.0 mode, the `"@container": "@set"` should be ignored. The rest of the steps in 12.2 should apply:

12.2.2: _compacted value_ = ["http://example.org/type"]
12.2.3: _alias_ = "type"
12.2.4: _as\_array_ = `false`
12.2.5: _add\_value_ adds ["http://example.org/type"] with _as\_array_ = `false`.

Looking at the _add\_array_ macro definition, it's not quite right: it should only add the first element from the array, if there is only one element, unless _as\_array_ is `true`. A recursive definition is probably better:

1) If _as\_array_ is `true`:
  1.1) If _key_ is not an entry in _object_, add a new entry for _key_ in _value_ who's value is a new empty array.
  1.2) Call this algorithm recursively passing _value_ and `false` for _as\_array_
2) Otherwise, if _value_ is an array, then for each element _v_ in _value, call this algorithm recursively passing _v_ and and _as\_array_
3) Otherwise:
  3.1) If _key_ is not an entry in _object_, add _value_ of the value of _key_ in _object.
  3.2) Otherwise, if the value of _key_ in _object_ is not an array, set it to a new array containing the original value followed by _value_
  3.3) Otherwise, add _value_ to the value of _key_ in _object_.

**Comment by roptat** [comment]
at which step is `@set` ignored?

**Comment by gkellogg** [comment]
> at which step is `@set` ignored?

More missing text, 12.2.4 should look for `@set` in the container unless processing mode is json-ld-1.0.

**Comment by roptat** [comment]
Thank you, it helped me pass the test :)

**Comment by gkellogg** [comment]
Updated in #440, see if that satisfies the issue.

**Comment by roptat** [comment]
it does, thank you!
