### ISSUE TITLE
toRdf tests e111 and e112

### ISSUE THREAD

**Issue by roptat** [w3c/json-ld-api#456]
Hi, I'm now working on the RDF part of the API, starting with toRdf. Most tests pass, but I still have some failures.

Test [e111](https://w3c.github.io/json-ld-api/tests/toRdf/e111-in.jsonld) looks a bit wrong to me, because I can't find a property with `#fragment-works` in [e111-out](https://w3c.github.io/json-ld-api/tests/toRdf/e111-out.nq). Same issue with e112.

**Comment by gkellogg** [comment]
The fact that it says "fragment-works" is a bit of a red herring for both these test; it's basically the same input used from before.

If you look at the intermediate expanded output you see the following:

```json
{ ...
  "http://example.com/vocabulary/./rel2##fragment-works": [{"@value":"#fragment-works"}]
...
}
```

Because "http://example.com/vocabulary/./rel2##fragment-works" is not a valid IRI (`##fragment-works` is not a valid fragment`), the property and associated value are dropped from the output when generating triples.

**Comment by roptat** [comment]
oh right, this shows I need better IRI validation... Thanks for the answer! We can close.
