### ISSUE TITLE
Invalid expansion test?

### ISSUE THREAD

**Issue by timothee-haudebourg** [w3c/json-ld-api#474]
The [expansion test 71](https://w3c.github.io/json-ld-api/tests/expand/0071-in.jsonld) is marked as positive and even has an [associated output](https://w3c.github.io/json-ld-api/tests/expand/0071-out.jsonld) although I don't understand why it is valid.

It is my understanding that, in a context definition, if the key looks like a compact IRI, its expansion must be the same as its associated expanded IRI mapping. So something like
```
"v": "http://example.com/vocab#",
"v:term": "v:somethingElse",
```
should be invalid since `http://example.com/vocab#term` is not equal to `http://example.com/vocab#somethingElse`.

This test is given with the `"specVersion": "json-ld-1.0"` option although I don't see anywhere in the context processing algorithm where this should matter in this case.

The test is also [rejected by the playground implementation](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%5B%7B%22v%22%3A%22http%3A%2F%2Fexample.com%2Fvocab%23%22%2C%22v%3Aterm%22%3A%22v%3AsomethingElse%22%2C%22v%3AtermId%22%3A%7B%22%40id%22%3A%22v%3AsomethingElseId%22%7D%7D%2C%7B%22v%3Aterm%22%3A%22v%3Aterm%22%2C%22v%3AtermId%22%3A%7B%22%40id%22%3A%22v%3AtermId%22%7D%7D%5D%2C%22v%3Aterm%22%3A%22value%20of%20v%3Aterm%22%2C%22v%3AtermId%22%3A%22value%20of%20v%3AtermId%22%7D&frame=%7B%7D&context=%7B%7D) (by the way, the processing mode option doesn't seem to be captured by the permalink).

**Comment by gkellogg** [comment]
Test 0071 is marked for specVersion "json-ld-1.0", meaning that it is incompatible with the 1.1 spec. This is because 1.1 requires that terms that look like IRIs or compact IRIs that don't expand to the `@id` associated with the term are now deemed invalid.

If you're implementing tests to the JSON-LD 1.1 spec, you should ignore all tests marked `"specVersion": "json-ld-1.0"` in test entry options.

Note the "specVersion" and "processingMode" are different. The processingMode can be "json-ld-1.0", for which a 1.1-complient implementation is expected to pass, but a 1.1 implementation will typically not pass any with `"specVersion": "json-ld-1.0"`.

**Comment by timothee-haudebourg** [comment]
> Note the "specVersion" and "processingMode" are different. The processingMode can be "json-ld-1.0", for which a 1.1-complient implementation is expected to pass, but a 1.1 implementation will typically not pass any with "specVersion": "json-ld-1.0"

I missed that, thanks.
