### ISSUE TITLE
Create Term Definition algorithm, possible imprecision step 11

### ISSUE THREAD

**Issue by timothee-haudebourg** [w3c/json-ld-api#475]
Step 11 of the [Create Term Definition Algorithm](https://www.w3.org/TR/json-ld11-api/#create-term-definition), it is said that
> If the `@protected` entry in `value` is `true` set the `protected` flag in `definition` to `true`

Strictly following this, a `"@protected": false` in a term definition is ignored.
However, this makes the [expansion test `pr13`](https://w3c.github.io/json-ld-api/tests/expand/pr13-in.jsonld) to fail.

**Comment by gkellogg** [comment]
Yes, it should set the `protected flag` to the value of the `@protected` entry, not only if it is `true`.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2020/2020-04-24-json-ld#section3-2).

- `RESOLVED:  Make editorial fix for @protected in Create Term Definition algorithm per api #475`
<details><summary><i class="differentiate">View the transcript</i></summary>
Rob Sanderson: <a href="https://github.com/w3c/json-ld-api/issues/475">https://github.com/w3c/json-ld-api/issues/475</a><br/>
Rob Sanderson: This issue is a micro-tweak to the algorithms.<br/>
Gregg Kellogg: The API document does not explicitly handle @protected: false cases.<br/>
… I believe this change is editorial.<br/>
Rob Sanderson: The change to the text should be very small.<br/>
… This is a change to a normative section that we have previously decided is editorial, because the tests aren’t changed. So we should fix this if we are comfortable given the transition request.<br/>
Ivan Herman: Does it affect any implementation already out there? I assume not.<br/>
Rob Sanderson: If you implemented strictly, you would fail the test. So this change is required to make implementations pass the test.<br/>
Proposed resolution: Make editorial fix for @protected in Create Term Definition algorithm per api #475 (Rob Sanderson)<br/>
Gregg Kellogg: +1<br/>
Rob Sanderson: +1<br/>
Ruben Taelman: +1<br/>
David I. Lehn: +1<br/>
Pierre-Antoine Champin: +1<br/>
Ivan Herman: +1<br/>
Resolution #2: Make editorial fix for @protected in Create Term Definition algorithm per api #475<br/>
Benjamin Young: +1<br/>
</details>

**Comment by gkellogg** [comment]
@timothee-haudebourg This is fixed in #481. Please let us know if that satisfies your concern.

**Comment by timothee-haudebourg** [comment]
It satisfies my concern, thanks.
