### ISSUE TITLE
Expansion Algorithm confusing Step 13.8.3.7.2.3 not covered by the expansion tests

### ISSUE THREAD

**Issue by timothee-haudebourg** [w3c/json-ld-api#477]
In the [Expansion Algorithm](https://www.w3.org/TR/json-ld11-api/#expansion-algorithm) I personally find the description of the Step 13.8.3.7.2.3 hard to understand:
> Initialize `index property values` to the concatenation of `re-expanded index`
with any existing values of `expanded index key` in `item`.

The variable `re-expanded index` holds a value object. I don't understand how to "concatenate" a value object with anything. I find the use of "any" confusing, does it mean "all", or "the first one you find"? Moreover, `expanded index key` is most likely to be an expanded IRI and I don't see any situation where it would appear in `item` (unless we consider the expanded keys in `item`? I'm lost).

In my implementation, I temporarily simplified this step by just defining `index property values` as `re-expanded index`. My plan was to come back to it while running the expansion tests, trying to understand reading the tests.

However I now pass all the tests without changing this part...

**Comment by gkellogg** [comment]
The result in `re-expanded index` may be a value object or a node reference, and _any_ values from `expanded index key` in `item` means _all_ values; the language is not incorrect (at least from an American English understanding), but "all" or "any and all" would be clearer.

And, the "concatenate" to `re-expanded index` should be represented in an array, so that _concatentation_ is clear.

A future version could restate this point by saying "Initialize `index property values` to an array containing `re-expanded index` followed by any or all existing values from `expanded index key` in `item`."

In practice, if there are such values they are already in an array, or there are no values.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2020/2020-04-24-json-ld#section3-2).

- `RESOLVED:  Improve wording to clarify any/all and concatenate per api #477`
<details><summary><i class="differentiate">View the transcript</i></summary>
Rob Sanderson: <a href="https://github.com/w3c/json-ld-api/issues/477">https://github.com/w3c/json-ld-api/issues/477</a><br/>
Gregg Kellogg: This is editorial. I suggested an improvement to the wording. This would not change the intention, only improve the wording.<br/>
Proposed resolution: Improve wording to clarify any/all and concatenate per api #477 (Rob Sanderson)<br/>
Ruben Taelman: +1<br/>
Gregg Kellogg: +1<br/>
Rob Sanderson: +1<br/>
Ivan Herman: +1<br/>
Pierre-Antoine Champin: +1<br/>
Benjamin Young: +1<br/>
Resolution #3: Improve wording to clarify any/all and concatenate per api #477<br/>
David I. Lehn: +1<br/>
</details>

**Comment by gkellogg** [comment]
@timothee-haudebourg This is fixed in #481. Please let us know if that satisfies your concern.

**Comment by timothee-haudebourg** [comment]
If I understand the new phrasing well, step 13.8.3.7.2.3 (doing the concatenation) is actually covered by, for instance, [expand#tpi07](https://w3c.github.io/json-ld-api/tests/expand-manifest.html#tpi07). The purpose of this step is to make sure that we don't end up missing the `'foo'` values for nodes `person/2` and `person/3` just because those nodes are indexed with `prop`, right?

If I'm correct, then I think it's good for me.
