### ISSUE TITLE
What is the purpose of `from map` in the Expansion Algorithm?

### ISSUE THREAD

**Issue by timothee-haudebourg** [w3c/json-ld-api#478]
The Expansion Algorithm requires a boolean `from map` variable as input. Its value is never changed across the expansion algorithms and is always set to `false`. There are only 3 occurrences of this variable in the whole API document. It doesn't seem to be used.

**Comment by gkellogg** [comment]
Step 13.8.3.6 of the Expansion Algorithm should pass `from map` as `true` when invoking the algorithm recursively. This seems to have gotten lost in some update.

As noted in the algorithm introduction, it is used to control reverting to a previous context, which can interfere with the semantics of index- id- and type-maps.

Removing it from my implementation causes [expand#tc013](https://w3c.github.io/json-ld-api/tests/expand-manifest.html#tc013) and [expand#tm008](https://w3c.github.io/json-ld-api/tests/expand-manifest.html#tm008) to fail, along with the toRdf versions of these tests.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2020/2020-04-24-json-ld#section3-2).

- `RESOLVED:  Add back from_map to 13.8.3.6 to recursive call for scoped contexts per api #478`
<details><summary><i class="differentiate">View the transcript</i></summary>
Rob Sanderson: <a href="https://github.com/w3c/json-ld-api/issues/478">https://github.com/w3c/json-ld-api/issues/478</a><br/>
Gregg Kellogg: We have a flag “from map” that was not used, but it is actually used, but got lost. It is required for inherited scoped context. If an implementation does not use this, it can not pass the tests. So this would require restoring the use of this flag to fix this.<br/>
Proposed resolution: Add back from_map to 13.8.3.6 to recursive call for scoped contexts per api #478 (Rob Sanderson)<br/>
Gregg Kellogg: +1<br/>
Rob Sanderson: +1<br/>
Ruben Taelman: +1<br/>
Benjamin Young: +1<br/>
Pierre-Antoine Champin: +1<br/>
Resolution #4: Add back from_map to 13.8.3.6 to recursive call for scoped contexts per api #478<br/>
</details>

**Comment by gkellogg** [comment]
@timothee-haudebourg This is fixed in #481. Please let us know if that satisfies your concern.

**Comment by timothee-haudebourg** [comment]
It's fine for the text, although it would be nice to have a test that catches the correct use of `from map`. I've been able to pass all the expansion tests without never using this variable.

**Comment by gkellogg** [comment]
In my implementation, if I don't pass `true` for `from map` from the Create Term Definition algorithm, tests [c013](https://w3c.github.io/json-ld-api/tests/expand-manifest.html#tc013) and [m008](https://w3c.github.io/json-ld-api/tests/expand-manifest.html#tm008) fail.
