### ISSUE TITLE
Expansion Algorithm, possible imprecision step 13.4.6.2

### ISSUE THREAD

**Issue by timothee-haudebourg** [w3c/json-ld-api#479]
While expanding `@included` step 13.4.6.2 it is said
> Set expanded value to the result of using this algorithm recursively passing active context, active property, value for element, base URL, and the frameExpansion and ordered flags, ensuring that the result is an array.

I believe the implementation is supposed to pass `@included` as active property instead of passing the current value. Otherwise, free floating literals inside the included block are automatically dropped, which makes the test [`expand/in07`](https://w3c.github.io/json-ld-api/tests/expand/in07-in.jsonld) to fail.

**Comment by gkellogg** [comment]
The syntax specification doesn't make it clear if the node containing the node with `@included` references the included nodes themselves, although in07 is consistent with their not being a relationship (which I think is the original intent).

Interestingly, my implementation does pass `active property`, but it doesn't end up creating such a relationship, but I can see how it might in another implementation.

Expansion could pass `@included` for `active property`, or `null`, which should have the same affect.

The Syntax document should be updated to clarify that there is no such relationship.

**Comment by pchampin** [comment]
To be fair, the syntax document states:

> When flattened, this will move the employee and contractor elements from the included block into the outer array.

but granted, this is a bit technical, and should be explained more clearly and sooner in the section.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2020/2020-04-24-json-ld#section3-2).

- `RESOLVED:  Clarify that in 13.4.6.2 for @included an implementation should pass null to avoid creating a reference, per api #479`
<details><summary><i class="differentiate">View the transcript</i></summary>
Rob Sanderson: <a href="https://github.com/w3c/json-ld-api/issues/479">https://github.com/w3c/json-ld-api/issues/479</a><br/>
Gregg Kellogg: It passes active property, while it shouldn’t. A node object contains an incl block, and has a rel to another block, the prop relationship should only hold to …. Passing null should be fine here.<br/>
Pierre-Antoine Champin: Does passing this active property have some impact on scoped contexts?<br/>
Gregg Kellogg: yes, by passing the active property, it is used in an unexpanded sense to find relationships in unscoped contexts, and also for informing the relationship. In a streaming impl, it could be used for creating that triple. I discovered that in my streaming impl. If you strictly follow the algorithm, it doesn’t create the issue, as can be seen by the implementations that pass the tests. It is however more correct to not pass an a<br/>
Ruben Taelman: ctive property.<br/>
Pierre-Antoine Champin: I was afraid that this would cause an unintended ripple effect.<br/>
Gregg Kellogg: Those things should be unrelated.<br/>
… I tried it in my implementation, putting null did not break anything.<br/>
… But it was required in my streaming implementation.<br/>
Proposed resolution: Clarify that in 13.4.6.2 for @included an implementation should pass null to avoid creating a reference, per api #179 (Rob Sanderson)<br/>
Gregg Kellogg: +1<br/>
Rob Sanderson: +1<br/>
Pierre-Antoine Champin: +1<br/>
Ivan Herman: +1<br/>
Ruben Taelman: +1<br/>
Benjamin Young: +1<br/>
Resolution #5: Clarify that in 13.4.6.2 for @included an implementation should pass null to avoid creating a reference, per api #479<br/>
</details>

**Comment by gkellogg** [comment]
@timothee-haudebourg This is fixed in #481. Please let us know if that satisfies your concern.

**Comment by timothee-haudebourg** [comment]
Yes, it is fine for me, thanks. Should I close the issue, or do I let you?

**Comment by gkellogg** [comment]
It will close automatically when the PR is merged, thanks!

**Comment by timothee-haudebourg** [comment]
Well I may have spoken too soon. Just too be sure, I tried to pass `null` as `active property` and failed to pass the tests [`expand/in07`](https://w3c.github.io/json-ld-api/tests/expand/in07-in.jsonld) and [`expand/in09`](https://w3c.github.io/json-ld-api/tests/expand/in07-in.jsonld). I'm not sure why yet, and I don't have time to look into it today, it will have to wait tomorrow...

**Comment by timothee-haudebourg** [comment]
Yes, so passing `null` as `active property` here is equivalent to passing on the current `active property` value, since there is no active property. It is *not* equivalent as passing `@included`. And according to step 4.1 (or step 19 for the expansion test in09) of the expansion algorithm
> If active property is null or @graph, drop the free-floating scalar by returning null.

So the value is dropped before being detected step 13.4.6.3. No error is raised and the test fails.
