### ISSUE TITLE
HTML baseURI and @context?

### ISSUE THREAD

**Issue by ajs6f** [w3c/json-ld-api#53]
We need to clarify the relationship between the base URI as derived from an embedding HTML document and a URI used for `@context`. Our work so far has addressed other kinds of URI resolution, but not this in particular.

**Comment by gkellogg** [comment]
We need to go a bit further and describe (syntax) and spec (api) how to retrieve a context when dereferencing the resolved URL results in an HTML document. This might include either/or fragment identifiers and `profile=http://www.w3.org/ns/json-ld#context`.

Resolving a relative IRI reference to a context would be similar to resolving a relative IRI within embedded JavaScript, IMO, which would use the base URL of the script element.

One interesting use case might be the following:

```html
<html>
  <head>
    <base href="http://example.org/" />
    <script type="application/ld+json;profile=http://www.w3.org/ns/json-ld#context">
      {
        "@context": {"@vocab": "http://schema.org/"}
      }
    </script>
    <script id="starthere" type="application/ld+json">
      {
        "@context": "",
        "@id": "",
        "@type": "Thing"
      }
    </script>
  </head>
</html>
```

If you expanded the document with target "starthere", it would load the context from itself, and use the first script, due to the type profile, setting `@vocab` to http://schema.org/. The result should be something like the following:

```json
[{
  "@id": "http://example.org/",
  "@type": ["http://schema.org/Thing"]
}]
```

**Comment by BigBlueHat** [comment]
@gkellogg your comment above seems to take this in a different direction than what I understood @ajs6f to be describing.

@ajs6f's description seems to match what I filed in https://github.com/w3c/json-ld-syntax/issues/134

Your comment seems to wide the scope (understandably) to "what if the context URL *is* the HTML document (or another HTML document with an embedded context)?"

Does that sound correct? If so, we should file a separate issue for the "extracting the context file from HTML" scenario.

Cool?

**Comment by gkellogg** [comment]
@BigBlueHat Yes, this gets back to our documentation issue, where we suggested that a JSON-LD document might reference an HTML document to get its context (or frame).

**Comment by BigBlueHat** [comment]
I'd suggest we close this as superseded by https://github.com/w3c/json-ld-syntax/issues/134#issuecomment-466494910 and the extraction of the "HTML as context file" expressed in #66.

@azaroth42 that seem sensible re: github issue management?

**Comment by BigBlueHat** [comment]
Closing as I think has been superseded by other issues mentioned above.
