### ISSUE TITLE
Tweak `@protected` algorithm to allow reuse of existing contexts w/o conflicts

### ISSUE THREAD

**Issue by dlongley** [w3c/json-ld-api#90]
A PR (https://github.com/digitalbazaar/jsonld.js/pull/316) in jsonld.js would prevent errors from being thrown when overriding protected terms if the override would result in the same definition as before. The only caveat to this is that if the new definition does not include `@protected`, this flag is carried forward to maintain the protection status. Otherwise, the definitions must match precisely, including any scoped contexts.

This tweak makes it much easier to reuse existing contexts that do not have any conflicting definitions in them with new contexts that use `@protected`. Without it, any existing `@context` that defines common things like aliases for `@id` or `@type` would be incompatible with contexts that protect those aliases.

The implementation change involved moving the `@protected` check to the end of the Create Term Definition algorithm and running a definition comparison check. All tests continue to pass with this change.

This change would still be a potentially valid interpretation of the current JSON-LD 1.1 syntax spec's text on `@protected`:

> A protected term definition is a term definition with a member `@protected` set to true. It generally prevents further contexts from overriding this term definition, either through a new definition of the same term, or through clearing the context with "@context": null.

As there is no "new definition of the same term", but rather, the same definition of the same term. The "same definition" is determined by comparing those things that a "term definition consists of" per the API spec. Again, the only caveat would be carrying forward `@protected` mode status even if not specified in the new definition.

So, if we want to do this, we may only need the above changes to the JSON-LD API spec, though we might want to add a clarifying sentence or two to the syntax spec to indicate that redefinitions of the same term with the same definition won't raise an error but that `@protected` status will remain unless the term is redefined without it when protection is not in effect.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-05-17-json-ld#section3-2).

- `RESOLVED:  Assuming the update to the algorithm is not controversial, protected definitions of terms do not raise an error when the term is redefined in exactly the same way, with the potential exception of not being protected`
<details><summary><i class="differentiate">View the transcript</i></summary>
3.2. Tweak @protected algorithm to allow reuse of existing contexts w/o conflicts<br/>
Dave Longley: <a href="https://github.com/w3c/json-ld-api/issues/90">https://github.com/w3c/json-ld-api/issues/90</a><br/>
Dave Longley: so this one is about reusing existing contexts<br/>
… the syntax spec says that a protected term definition with @protected: true<br/>
… it prevents it being overridden<br/>
… possibly by setting context to null<br/>
… what is prohibited is introducing other definitions<br/>
… but what happens when new terms come in<br/>
… what this change could provide is allowing using 1.0 contexts alongside protected<br/>
… so, things that define aliases for id/type<br/>
Rob Sanderson: +1 to this issue<br/>
Dave Longley: you can’t currently bring those in with protected, because that throws an error<br/>
… because you’re trying to redefine terms–even though the result would be the same<br/>
… so the only caveat is reusing old contexts won’t come with @protected set<br/>
… so in that case, you just keep @protected flag to on<br/>
… so update the API to switch where we check that protected is set, not update existing terms that are identical–modulo the protected flag<br/>
David Newbury: it does seem to make complete sense<br/>
… I’d want gkellogg to weigh in<br/>
… to get another implementer’s input on this<br/>
Dave Longley: so, the only sticky issue is two scoped contexts, then you have to do a full comparison<br/>
Rob Sanderson: if they’re by value rather than by reference…yeah…that would be rough<br/>
… so with the caveat that the editors are OK<br/>
… here’s a proposal<br/>
Proposed resolution: Assuming the update to the algorithm is not controversial, protected definitions of terms do not raise an error when the term is redefined in exactly the same way, with the potential exception of not being protected (Rob Sanderson)<br/>
David Newbury: +1<br/>
Jeff Mixter: +1<br/>
Dave Longley: +1<br/>
Rob Sanderson: +1<br/>
Simon Steyskal: +1<br/>
David I. Lehn: +1<br/>
Benjamin Young: +1<br/>
Resolution #3: Assuming the update to the algorithm is not controversial, protected definitions of terms do not raise an error when the term is redefined in exactly the same way, with the potential exception of not being protected<br/>
</details>

**Comment by gkellogg** [comment]
Closed via #92 and w3c/json-ld-syntax#190.
